### ISSUE TITLE
[1.12.2] MC crashing at start

### ISSUE THREAD

**Issue by clanec15** [MC-U-Team/Music-Player#10]
I have the mod activated and when i try to start it it crashes at Forge load
I have the 
Music-Player-1.12.2-2.0.0.9

**Comment by HyCraftHD** [comment]
Crashlog?

**Comment by clanec15** [comment]
[crash-2019-07-04_13.17.30-client.txt](https://github.com/MC-U-Team/Music-Player/files/3363444/crash-2019-07-04_13.17.30-client.txt)

**Comment by HyCraftHD** [comment]
This is an error of an other mod. 
![grafik](https://user-images.githubusercontent.com/7681220/60734714-17aea680-9f51-11e9-9daf-33ba55829189.png)

Please report to them
