### ISSUE TITLE
[Request] 1.7.10 Backport

### ISSUE THREAD

**Issue by PlayfulPiano** [MC-U-Team/Music-Player#1036]
### Detailed description of the feature

Hey there. I've been a major fan of the music player mod back when I was playing 1.20 modpacks. But for the past few months I've gotten absorbed into the abyss that is gregtech new horizons. Sadly, a big type of mod which is lacking for that version is a proper youtube playlist/playback music mod.

I wanted to ask if you could possibly backport the latest of MusicPlayer to 1.7.10. That way ppl who are doing 1.7.10 modpacks can have access to an integrated music player without having to keep for example a browser window open in the bg.

Thank you!

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
I do not have time nor knowledge to do that for a version that is nearly 10 years old.
I'm open to PR if you want to do that.
