### ISSUE TITLE
[MC-1.19.2] YouTube Support not working

### ISSUE THREAD

**Issue by NathxnAzuur** [MC-U-Team/Music-Player#1037]
### Bug description and reproduction steps

When I want to search, or add a music with a YouTube link, it returns me an error.

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/105375222/3169ecee-91a0-401d-aad8-7771de01ac60)
![image](https://github.com/MC-U-Team/Music-Player/assets/105375222/ba9b6b40-dc46-4f8e-836d-d8fef74eb376)

### Used minecraft version

1.19.x

### Used forge or fabric version

43.2.14

### Used mod version

2.5.1.202

**Comment by HyCraftHD** [comment]
Use the latest 1.19.2 version: https://www.curseforge.com/minecraft/mc-mods/music-player/files/5302426

**Comment by HyCraftHD** [comment]
https://www.curseforge.com/minecraft/mc-mods/music-player/files/5302426
