### ISSUE TITLE
[MC-Version] 1.20.1 bug

### ISSUE THREAD

**Issue by pikminyun** [MC-U-Team/Music-Player#1038]
### Bug description and reproduction steps

it wont work ig?
i download the mod and its dependency and it wont work like it just wont give the items or even register that there in that game 
(yes im launching modded)

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/172233316/983aebd5-fe05-4990-85b6-0782acfcee75)
![image_2024-06-09_220936523](https://github.com/MC-U-Team/Music-Player/assets/172233316/1c33bb7f-6aa2-4be6-a442-2e00e8a35118)

### Used minecraft version

1.20.x

### Used forge or fabric version

fabric

### Used mod version

1.20.1

**Comment by InklingYoshi584** [comment]
The music player is just a music player that can be accessed in the pause menu in the top right corner, it gives absolutely no items, it is just a function to play music, nothing else
