### ISSUE TITLE
my music stops at 30 seconds

### ISSUE THREAD

**Issue by PikachuLuke5** [MC-U-Team/Music-Player#1040]
### Bug description and reproduction steps

my music skips at 30 seconds.
1. add music
2. play it
3. wait untill 30
4. just cry

This happened to me a couple of times.

### Log files and Screenshots

I have no files.

### Used minecraft version

1.20.x

### Used forge or fabric version

0.15.11

### Used mod version

2.7.0.256

**Comment by HyCraftHD** [comment]
Please upload the debug.log file

**Comment by HyCraftHD** [comment]
Closing the issue because no reply
