### ISSUE TITLE
[MC-1.20.1] Loading information for a YouTube track failed, .etc

### ISSUE THREAD

**Issue by InklingYoshi584** [MC-U-Team/Music-Player#1050]
### Bug description and reproduction steps

Half a year ago, the YouTube track loading function worked perfectly fine, but it suddenly stopped working now, as shown in the picture down there, I tried to reinstall the track, but the track searching function stopped working too, EVEN the link entering box.

## Note:
There is also a Reddit post that discussed this problem, but there aren't any replies on how to fix this, only the reports.
The reddit link is here: https://www.reddit.com/r/feedthebeast/comments/1bf4dwc/music_player_not_fetching_anything_from_youtube/

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/125667328/18667895-19e8-4037-b21d-c08033fa0cf5)
![image](https://github.com/MC-U-Team/Music-Player/assets/125667328/b9046e76-276e-499c-9282-8f4ab7718f90)

### Used minecraft version

1.20.x

### Used forge or fabric version

47.2.17

### Used mod version

2.7.0.236

**Comment by HyCraftHD** [comment]
Hello, please update to the latest version which is 1.20.1-2.7.0.256
