### ISSUE TITLE
[1.20.4] The songs don't start; every song is skipped

### ISSUE THREAD

**Issue by SMonroeC** [MC-U-Team/Music-Player#1051]
### Bug description and reproduction steps

Here's a recording of what happens:
https://youtu.be/1_5vRRTKi4E
Upon pressing play, the playlist goes from song to song quickly, with no audio. The pause button doesn't work, but the shuffle, skip-forward, and skip-backward buttons do work. The repeat-once button causes the playlist to stop skipping songs, but they still don't advance in seconds or have any audio.

### Log files and Screenshots

[latest.log](https://github.com/user-attachments/files/16150938/latest.log)

### Used minecraft version

1.20.x

### Used forge or fabric version

49.0.50

### Used mod version

2.7.1.257

**Comment by xxxkingxl** [comment]
bro, I cant play yt music any more, wtf are youtube doing?

**Comment by This0Is0Faker** [comment]
Yotube is trying to get this mod down?

**Comment by lolboibye** [comment]
> Yotube is trying to get this mod down?

are your srs?!

**Comment by 533kr** [comment]
Not sure if this is proper reporting etiquette, but I actually came here to report this very issue myself as well--here's my own [video ](https://youtu.be/zvl9v147qdQ)showing that this is also happening on 1.20.1 Forge. Mod version I have is `2.7.0.256`.

If I should also post a new bug for this, let me know, but atm I feel like it might be more helpful to provide additional info under one entry?

**Comment by xxxkingxl** [comment]
> Not sure if this is proper reporting etiquette, but I actually came here to report this very issue myself as well--here's my own [video ](https://youtu.be/zvl9v147qdQ)showing that this is also happening on 1.20.1 Forge. Mod version I have is `2.7.0.256`.
> 
> If I should also post a new bug for this, let me know, but atm I feel like it might be more helpful to provide additional info under one entry?

yes, same one my side but very fast

**Comment by xxxkingxl** [comment]
I am on fabric 1.20.4
And on my side in goes troug songs very fast in the same way as other people (it goes a lot faster on my side)
