### ISSUE TITLE
[1.20.1] Songs not loading and getting skipped, tried everything

### ISSUE THREAD

**Issue by MrProton657** [MC-U-Team/Music-Player#1052]
### Bug description and reproduction steps

every song gets skipped, tried restarting router, using vpn, cleaning temp folder and appdata of your mod. 

mc 1.20.1
u_team_core-forge-1.20.1-5.1.4.312
music_player-forge-1.20.1-2.7.0.256
latest version of your mod.

danke im vorraus

### Log files and Screenshots

[latest.log](https://github.com/user-attachments/files/16183718/latest.log)

### Used minecraft version

1.20.x

### Used forge or fabric version

47.2.20

### Used mod version

2.7.0.256

**Comment by HyCraftHD** [comment]
Update to the latest versions, should be fixed there
