### ISSUE TITLE
[1.12.2] Conflict issues with FancyMenu Mod

### ISSUE THREAD

**Issue by GeeLawjik** [MC-U-Team/Music-Player#108]
**Describe the bug**
UI buttons not working (only the settings button works), can't type in text boxes + double buttons.
![Capture](https://user-images.githubusercontent.com/75605236/101325833-63e2d200-383a-11eb-9ed4-515332031343.PNG)
Added this mod with The Pixelmon Modpack on CurseForge

**Versions**
- Mod version: 2.1.1.108
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2854
- UTeamCore version: 2.2.5.147

**Comment by HyCraftHD** [comment]
1.12.2 is outdated so this will not be fixed
