### ISSUE TITLE
[MC-Version] 1.20.4

### ISSUE THREAD

**Issue by ezzydude** [MC-U-Team/Music-Player#1088]
### Bug description and reproduction steps

when i play a song it just skips too the next one without playing the song

### Log files and Screenshots

https://github.com/user-attachments/assets/da03ac91-fd44-4675-9c32-dd95fe3375be

### Used minecraft version

None

### Used forge or fabric version

fabric

### Used mod version

2.7.1.257

**Comment by HyCraftHD** [comment]
Please update to the latest version.
Feel free to reopen if the issue still persist
