### ISSUE TITLE
[MC-1.8.9] A crash that I don't understand at all

### ISSUE THREAD

**Issue by Snivine** [MC-U-Team/Music-Player#109]
**Description**
It's a crash, probably due to incompatibility, it doesn't happens without UTeamCore and Music Player

1. Create a Vanilla Profile/MultiMC instance with the following mods: (look at screenshots)
2. Open the instance
3. Watch minecraft die

**Expected behavior**
The game should start up normally

**Screenshots**
![image](https://user-images.githubusercontent.com/72054019/102544822-00974200-407b-11eb-9abd-0846484475aa.png)

**Versions**
- Mod version: 2.1.107
- Minecraft version: 1.8.9
- Forge version: 11.15.1.2318
- UTeamCore version: 1.8.9-1.3.0.63

**Logs**
Two different crashes happened due to this:
https://paste.ee/p/e7F26
https://paste.ee/p/LraJ1

**Comment by HyCraftHD** [comment]
This is a known incompatibility with patcher

**Comment by HyCraftHD** [comment]
Should be fixed with this version https://www.curseforge.com/minecraft/mc-mods/music-player/files/3841508
