### ISSUE TITLE
Music Player crashing game

### ISSUE THREAD

**Issue by ghost** [MC-U-Team/Music-Player#11]
This issue never occurred for me before. This is entirely new to me.
When the game crashes, the Java Runtime is still active in task manager. Once it's closed, the Minecraft Launcher pops up and throws at me this error: "The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen"

Image of the overlay of the music player before it crashes: 
![image](https://user-images.githubusercontent.com/32934452/61944529-8c03c500-afa6-11e9-8413-f8c275e1f854.png)

Other: This mod never had any interference with other mods.  The issue itself is the mod or the library, I'm not sure.

**Comment by HyCraftHD** [comment]
What version is the music player, the uteamcore and forge?
Also please post the crashlog and the debug crash log file from logs/debug.log

**Comment by HyCraftHD** [comment]
Closed because of now response
