### ISSUE TITLE
Youtube Songs are restarting from 0 or skip 

### ISSUE THREAD

**Issue by Blackstorm1411** [MC-U-Team/Music-Player#1100]
### Bug description and reproduction steps

Mp3 and soundcloud songs are working but youtube songs are keep starting from 0 when i playor skip to 1 min or it skips this youtube song i updated the mod version u Team core and music player and its still not working HELP i cant listen to music :(

### Log files and Screenshots

https://github.com/user-attachments/assets/75460238-89d9-418c-bb4b-475888f8263c

### Used minecraft version

1.21.x

### Used forge or fabric version

Fabric

### Used mod version

Musicplayer : 2.7.1.272 Uteamcore : 5.6.0.317

**Comment by Blackstorm1411** [comment]
i Testet other version for the musicplayer mod( in 1.21 ) and its still not working so its for all 1.21 versions

**Comment by Spacedestructor** [comment]
I have the same problem with mod version 2.3.4.264 and u team core version 4.0.1.309 on minecraft version 1.18.2
as far as i can tell this affects either all versions (which would indicate its not the mods fault) or at least a wide range of mod versions of multiple minecraft versions of this mod are impacted.

**Comment by HyCraftHD** [comment]
The issues #1100 and #1101 seem to be related. Youtube changed something in their scripts again that broke the youtube playback. A fix is on the way

**Comment by HyCraftHD** [comment]
Fixed with these versions: 
![image](https://github.com/user-attachments/assets/d3d1fcb5-ac5a-4ca9-96f7-4a4d536f22b3)
