### ISSUE TITLE
[1.16.1] Youtube search doesn't work

### ISSUE THREAD

**Issue by DeckerExpert** [MC-U-Team/Music-Player#115]
**Describe the bug**
Whenever i try to search anything in Youtube, it doesnt work and only said nothing found. Soundcloud works fine and works. 

**To Reproduce**
Install the mod and try to search anything on youtube's search bar.

**Expected behavior**
Youtube would give me results and let me play the songs i want. What I got is a No Matches Found error.

**Versions**
- Mod version: 2.2.0.88 
- Minecraft version: 1.16.1
- Forge version: 32.0.108
- UTeamCore version: 3.1.4.182

**Comment by HyCraftHD** [comment]
1.16.1 is unsupported. Please use 1.16.4 / 1.16.5
