### ISSUE TITLE
[MC-Version] 1.19.3

### ISSUE THREAD

**Issue by Jazz-k-tok** [MC-U-Team/Music-Player#1196]
### Bug description and reproduction steps

When I try to search for a song on YouTube I get an error, it says ''something went wrong when looking up the track''
I have already tried to reinstall the mods but still get the error

### Log files and Screenshots

![imagen_2024-08-16_165114097](https://github.com/user-attachments/assets/3409bdc1-c739-46cd-bb90-1da06754b9f2)

### Used minecraft version

1.19.x

### Used forge or fabric version

Forge 44.1.23

### Used mod version

1.19.3-2.5.2.195

**Comment by HyCraftHD** [comment]
Use 1.19.2 or 1.19.4.
1.19.3 is unsupported
