### ISSUE TITLE
[Enhancement] Add "radio" block.

### ISSUE THREAD

**Issue by SpadeCA** [MC-U-Team/Music-Player#121]
Trying to get an old ComputerCraft script working again but I need a block akin to the one from OpenBlocks. Would it be possible to make a block that has:

1. A GUI for URL's and sound control.
2. Option to make sound volume radius based on block(s)/global.
3. Redstone controlled.
4. (Optional) ComputerCraft support to change URL's/Volume/Power via a peripheral (I would pay for this).

If not, I still appreciate the great mod, thanks for the hard work.

**Comment by psynyde** [comment]
thn it wont be a client sided mod and you can't use that on servers..

**Comment by SpadeCA** [comment]
That's fine, completely understand.
