### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by chickenbiscuts** [MC-U-Team/Music-Player#16]
evertimeopen my game with this mod it just crashes and it kept saying "A error when setting up this mod

**Comment by MrTroble** [comment]
Hello chickenbiscuts,

can you please send us your crash report and/or log.
Thank you for reporting this issue.

Cheers
~MrTroble

**Comment by chickenbiscuts** [comment]
Here is the Log
[log.txt](https://github.com/MC-U-Team/Music-Player/files/3498186/log.txt)

**Comment by MrTroble** [comment]
Which version are you on?
Could you send me the
Forge version
Minecraft version
and Mod version
please

**Comment by HyCraftHD** [comment]
Seems like your are using an old music player version for the latest forge builds. Please use 2.0.2.30 version if you are using a forge versions after 28.0.45: 
Musicplayer-1.14.4-2.0.2.30

**Comment by chickenbiscuts** [comment]
ok

**Comment by chickenbiscuts** [comment]
I'll see if this works

**Comment by MrTroble** [comment]
I will close this issue for now if the issue persists please reopen this issue.

Cheers
~MrTroble
