### ISSUE TITLE
[1.8.9] its saying : gui.musicplayer. . . etc

### ISSUE THREAD

**Issue by Doloro1978** [MC-U-Team/Music-Player#177]
**Describe the bug**
instead of search it say something like gui.musicplay or stuff like that 

**To Reproduce**
1. Go to 'the menu'

**Expected behavior**
it to say "search" or something

**Screenshots**
![image](https://user-images.githubusercontent.com/74507512/110838966-f9a75680-829a-11eb-8f6b-8ae8c512d7bc.png)

**Versions**
- Mod version: latest 
- Minecraft version: 1.8.9
- Forge version: latest 1.8.9
- UTeamCore version: latest

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
What other mods do you have installed? Maybe related to #55

**Comment by Doloro1978** [comment]
> What other mods do you have installed? Possible related to #55

labymod and thats all

**Comment by Doloro1978** [comment]
> > What other mods do you have installed? Possible related to #55
> 
> labymod and thats all

I removed it and its still the same

**Comment by HyCraftHD** [comment]
What forge version do you have installed?
Can you send me the debug.log from the start?

**Comment by Doloro1978** [comment]
> What forge version do you have installed?
> Can you send me the debug.log from the start?

I have 1.8.9 - 11.15.1.1722 install
and where can i find the debug.log file?

**Comment by HyCraftHD** [comment]
logs/debug.log

**Comment by HyCraftHD** [comment]
Please try to forge version: 11.15.1.2318 (latest)

**Comment by Doloro1978** [comment]
> Please try to forge version: 11.15.1.2318 (latest)

do you have discord so i can show you

**Comment by HyCraftHD** [comment]
Well you can join my discord: https://discord.hycrafthd.net
But currently I don't have time to check that.
Have you tried the newer forge version?

**Comment by Doloro1978** [comment]
> Well you can join my discord: https://discord.hycrafthd.net
> But currently I don't have time to check that.
> Have you tried the newer forge version?

yep

**Comment by HyCraftHD** [comment]
Do you use the curseforge launcher?

**Comment by Doloro1978** [comment]
> Do you use the curseforge launcher?

nope but i can try

**Comment by HyCraftHD** [comment]
If you use the normal minecraft installation you can find the log on windows here: %appdata%/.minecraft/logs/debug.log or fml-log

If you are not on windows you should find the .minecraft folder in your home folder

**Comment by Doloro1978** [comment]
> If you use the normal minecraft installation you can find the log on windows here: %appdata%/.minecraft/logs/debug.log or fml-log
> 
> If you are not on windows you should find the .minecraft folder in your home folder

I am on windows,

**Comment by Doloro1978** [comment]
> If you use the normal minecraft installation you can find the log on windows here: %appdata%/.minecraft/logs/debug.log or fml-log
> 
> If you are not on windows you should find the .minecraft folder in your home folder

https://pastebin.com/pcjZq3wB

**Comment by Doloro1978** [comment]
> If you use the normal minecraft installation you can find the log on windows here: %appdata%/.minecraft/logs/debug.log or fml-log
> 
> If you are not on windows you should find the .minecraft folder in your home folder

So?

**Comment by HyCraftHD** [comment]
Can you run it without labymod and send me the log and confirm that it still does not show the translated strings?

**Comment by Doloro1978** [comment]
> Can you run it without labymod and send me the log and confirm that it still does not show the translated strings?

Still not showing the translated strings https://pastebin.com/NZkHYw2y

**Comment by HyCraftHD** [comment]
Okay I tried it if these mod versions (same as yours)
![image](https://user-images.githubusercontent.com/7681220/111007215-9f87bd80-838e-11eb-8dce-b20edab68a63.png)
and the same forge version and cannot reproduce that bug.
![image](https://user-images.githubusercontent.com/7681220/111007263-b9c19b80-838e-11eb-9c48-afaf565cfd58.png)


The only thing I can think of is that the resource pack that is loaded may cause some issues. Apart from that I have no clue why that happens.

**Comment by Doloro1978** [comment]
Let me try with it clean

**Comment by Doloro1978** [comment]
> Okay I tried it if these mod versions (same as yours)
> ![image](https://user-images.githubusercontent.com/7681220/111007215-9f87bd80-838e-11eb-8dce-b20edab68a63.png)
> and the same forge version and cannot reproduce that bug.
> ![image](https://user-images.githubusercontent.com/7681220/111007263-b9c19b80-838e-11eb-9c48-afaf565cfd58.png)
> 
> The only thing I can think of is that the resource pack that is loaded may cause some issues. Apart from that I have no clue why that happens.

could we hob in a fast discord call and i screen share or are you busy?

**Comment by HyCraftHD** [comment]
It's 1 am for me so too late. The best way to figure it out would probably that you send me your mods folder and the forge installation folder. But it seems to be a weird issue.
Have you tried this resource pack as a workaround (#55)
https://github.com/MC-U-Team/Music-Player/files/4753993/Fix.for.Music.Player.zip

**Comment by HyCraftHD** [comment]
As 1.8.9 is outdated this will not be fixed.
