### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by brandon956** [MC-U-Team/Music-Player#179]
mod skips songs songs dont play how do i fix this?

**Comment by HyCraftHD** [comment]
Please use the issue template. I need to minecraft version, the uteamcore and musicplayer version and the debug.log when song was skipped please.

**Comment by dirtyltu** [comment]
I had the same problem but I found a way to go around it. when you start the playlist start clicking on the bar where it's showing how much time is left and that solved the problem for me.

**Comment by HyCraftHD** [comment]
Can you @dirtyltu send me the information though so I can see if I can fix it?

**Comment by dirtyltu** [comment]
minecraft version: 1.16.5
Music player version: 2.3.1.123
uteamcore version: 3.2.0.194
and for the debug.log I cant find it

**Comment by HyCraftHD** [comment]
Thanks. The song link that was skipped is important

**Comment by dirtyltu** [comment]
https://www.youtube.com/watch?v=nPfOnJIMd8Y&list=PL1Ou2nr60yywfsFhqBnliDeY3l5Hkv29J
https://www.youtube.com/watch?v=8sAKC90Ol1k&list=PL1Ou2nr60yyyJr52tlSxprELuYkjyg_xo
both of these playlist

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://user-images.githubusercontent.com/7681220/115970094-9f0f4480-a540-11eb-8b7e-aa2aecc51725.png)
