### ISSUE TITLE
[1.14] Crash on startup

### ISSUE THREAD

**Issue by salmornal** [MC-U-Team/Music-Player#18]
Put this into my mods folder but the game crashes every time i try to start.

**Comment by HyCraftHD** [comment]
Crashreport and used versions please

**Comment by salmornal** [comment]
So, i use minecraft forge 1.14.4-28.0.45 and have uteam installed too. Only other thing i used was optifine 1.14.4_HD_U_F4_pre2. By the way, updating the version of forge caused it to stop crashing, although i can't get to the title screen since it is incompatible. Before it just didn't boot properly.

**Comment by HyCraftHD** [comment]
Sure the latest version of music player is only compatible since 1.14.4-28.0.48 because of a change in the class packages. Optifine is still not compatible with forge 1.14.4.
I'll close it for now, when a crash occured again please let me know and reopen.

**Comment by HyCraftHD** [comment]
The latest music player version is only compatible with the latest forge version, because that fixes a class package change. Optifine is still not compatible with 1.14.4. I'll close for now. Please let me know and reopen the issues if any other crash occur.
