### ISSUE TITLE
[1.11] Invalid version

### ISSUE THREAD

**Issue by alex233187** [MC-U-Team/Music-Player#183]
Hello, i have the problem that i CANNOT add any music at all, no matter what i try.
I play on a Server (1.11.2)
 
![2021-03-26_17 11 44](https://user-images.githubusercontent.com/81432879/112661143-7cf9a800-8e56-11eb-8360-fbdf240725dc.png)

what can i do? please help

**Comment by HyCraftHD** [comment]
1.11.2 is not supported anymore.
Only 1.8.9, 1.12.2, 1.14.4, 1.15.2, 1.16.4 and 1.16.5 are supported
