### ISSUE TITLE
[1.16.4] Songs get skipped

### ISSUE THREAD

**Issue by emanuele246gi** [MC-U-Team/Music-Player#184]
**Describe the bug**
When I try to listen to music, most of them get skipped from two to even ten songs

**To Reproduce**
1. Listen to music until this occurs

**Versions**
- Mod version: 2.3.0.122
- Minecraft version: 1.16.4
- Forge version: 35.1.37
- UTeamCore version: 3.1.17.192

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://user-images.githubusercontent.com/7681220/115970099-a7677f80-a540-11eb-9331-a558fd6c4348.png)
