### ISSUE TITLE
Clicking button to show overlay does nothing

### ISSUE THREAD

**Issue by ESTPlayer** [MC-U-Team/Music-Player#2]
What should happen: i should be able to add music/url etc
what happens: console spams with this error and overlay doesnt open:
log:https://paste.ee/p/LI7nF

player version: Music-Player-1.0.0-2 
core version:U-Team-Core-1.12.2-1.1.2-60
minecraft: 1.12.2
forge: 2705

**Comment by HyCraftHD** [comment]
Closed because no response and not reproducible
