### ISSUE TITLE
The music wont play

### ISSUE THREAD

**Issue by simonmich** [MC-U-Team/Music-Player#20]
![image](https://user-images.githubusercontent.com/49367838/64430623-ec634780-d0b8-11e9-970b-93d822278b2a.png)
When I try pressing the play button, the song just disappears. I am playing in 1.12.2 with just optifine and the other required mod.

**Comment by HyCraftHD** [comment]
Please use the 2.0.x.x versions of music player as the 1.0.x.x versions no longer work because of changes in the youtube api.

**Comment by simonmich** [comment]
Ok thank you my good fellow

**Comment by simonmich** [comment]
But will that work with 1.12.2? I am also using optifine with it.

**Comment by HyCraftHD** [comment]
Sure there is a new version available.

**Comment by simonmich** [comment]
When I press play, nothing happens?

**Comment by HyCraftHD** [comment]
Where do you press? Screenshot pls?

**Comment by simonmich** [comment]
Do you have discord? I have a video clip I can rather send..

**Comment by HyCraftHD** [comment]
Sure: https://discord.hycrafthd.net

**Comment by Nov4Specter** [comment]
So, did it get fixed? 
I feel left out here :D

I'm having the same issue, when i press the play button it skips the songs

**Comment by MrTroble** [comment]
This was not an issue ... this was due to the misuse of the mode.

**Comment by MrTroble** [comment]
Keep in mind that you have to add music to the playlist

**Comment by malamura1** [comment]
I have the same problem. It skiped the song in the playlist.

**Comment by MrTroble** [comment]
Can you tell me what exactly you are doing? Could you provide some screenshots ?

Thanks in advance

**Comment by malamura1** [comment]
I can. But I use forge 1.12.2 -14.23.5.2768 and it does not play it skiped. I dont thinkt taht a screenshot shows that.

**Comment by malamura1** [comment]
and i use the version 2.0

**Comment by MrTroble** [comment]
This seem to be issues from youtube API changes

**Comment by MrTroble** [comment]
we will update our dependencies asap :) Thank you for reporting

**Comment by Nov4Specter** [comment]
oow, that puts me at ease.
I was stressing that i did something wrong xD

Thank you <3

**Comment by malamura1** [comment]
Thank you guys. its cool that you do your (Job) fast.

**Comment by MrTroble** [comment]
See #22 for updates

**Comment by MrTroble** [comment]
The fixed 1.12 should be updatet in a minute! Again thanks for reporting
If you have any other problems please revere to #22 or #23. I will close this for now :)

Cheers
~MrTroble
