### ISSUE TITLE
[1.16.5] Mod won't work on server

### ISSUE THREAD

**Issue by rebootGrace** [MC-U-Team/Music-Player#201]
I've added the mod files to both my mods folder and my server's mods folder and F8 is not bringing anything up. I have also installed uteamcore on both my mods folder and my server's mods folder

**Versions**
- Mod version: 1.16.5
- Minecraft version: 1.16.5
- Forge version: 1.16.5
- UTeamCore version: 1.16.5

**Comment by HyCraftHD** [comment]
What does not work?
Have you checked in the key binds, that no other key has F8 bound? If not try to change the key.
Furthermore the mod is client side.

**Comment by HyCraftHD** [comment]
Close because lack of response
