### ISSUE TITLE
Mod translate - zh_tw

### ISSUE THREAD

**Issue by EvanHsieh0415** [MC-U-Team/Music-Player#207]
Can I translate this mod into traditional Chinese?
[Dropbox Link here](https://www.dropbox.com/s/hvt8oyu2byrzztk/zh_tw.json)

**Comment by HyCraftHD** [comment]
Sure. Thanks! Do you want to make a pr for credits?

**Comment by EvanHsieh0415** [comment]
yes I want it!
thanks.
.w.

**Comment by HyCraftHD** [comment]
Then go ahead! Thanks

**Comment by EvanHsieh0415** [comment]
Added (#208 )

**Comment by HyCraftHD** [comment]
Thanks! Merged. Will push an updated to curseforge soon
