### ISSUE TITLE
[1.12.2] Instant skip

### ISSUE THREAD

**Issue by PAVEL2000official** [MC-U-Team/Music-Player#241]
Hello U Team!

I just downloaded the Music Player mod and when i tried to play a song it just skips to the next song, and because of that i cant listen songs.

Versions
- Mod version: 2.1.1.132
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2854
- UTeamCore version: 2.2.5.147

I dont have any crashes.

**Comment by HyCraftHD** [comment]
Hello,
Can you please link the the song urls that are not working?

**Comment by PAVEL2000official** [comment]
Hello,
I used like 10/15 different songs and all of them didn't work, i don't think the problem is in the songs
but here 5 of the songs i tried -

https://www.youtube.com/watch?v=XHvS2PZxztU&t
https://www.youtube.com/watch?v=9B9-DdNm3Vk&list=PLRf_iIa-1tUVUx1ox5HxuoaFfdkVAMUtN
https://www.youtube.com/watch?v=1MB7QiGwjmQ&t
https://www.youtube.com/watch?v=ou-rVp6EbhM
https://www.youtube.com/watch?v=g5sukHe4A3A

**Comment by HyCraftHD** [comment]
Okay cannot reproduce with these videos. Works fine for me.
Can you send me the debug log when the issue occured?

**Comment by PAVEL2000official** [comment]
How do i see the debug log?

**Comment by HyCraftHD** [comment]
In your minecraft directory / or the curseforge minecraft installation directory go to the logs directory and upload the debug.log file

**Comment by HyCraftHD** [comment]
In 1.12.2 there is maybe no debug.log file then use the latest.log or fml-latest.log

**Comment by PAVEL2000official** [comment]
So like do i send the file or?

**Comment by HyCraftHD** [comment]
Yes, you can just drag it in here and will is updated as a response

**Comment by PAVEL2000official** [comment]
[debug.log](https://github.com/MC-U-Team/Music-Player/files/6642028/debug.log)

**Comment by PAVEL2000official** [comment]
i think thats the right file

**Comment by PAVEL2000official** [comment]
there may be alot of other useless logs cuz of my other mods so i hope you find the thing u r searching

**Comment by HyCraftHD** [comment]
Yes, its an issue with the native libraries lavaplayer uses.
Seems like 32 bit is not supported and maybe windows 7 is an issue too.
Is your system 64bit? If so please install the 64 bit jdk and set that in the minecraft launcher and try again.

**Comment by PAVEL2000official** [comment]
okay but im little stupid and how do i install 64 bit? i know that my pc supports it but i dont know how

**Comment by HyCraftHD** [comment]
Do you use the default minecraft launcher?

**Comment by PAVEL2000official** [comment]
nope , is this big issue?

**Comment by HyCraftHD** [comment]
Well it's different then. What launcher do you use?

**Comment by PAVEL2000official** [comment]
TLauncher

**Comment by HyCraftHD** [comment]
Alright, this launcher is not supported.

The only think I can help you with is uninstall your current java and install e.g. this one https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_windows_hotspot_8u292b10.msi from https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot

**Comment by PAVEL2000official** [comment]
okay ill try this

**Comment by PAVEL2000official** [comment]
its installed now

**Comment by PAVEL2000official** [comment]
what do i do now?

**Comment by HyCraftHD** [comment]
Start and try again. But sorry I cannot help here as I do not support cracked launchers

**Comment by PAVEL2000official** [comment]
ill download the official launcher and ill tell you if its working or not

**Comment by PAVEL2000official** [comment]
its working now! thanks for helping me :)
