### ISSUE TITLE
1.12.2 - Soundcloud songs not playing

### ISSUE THREAD

**Issue by Cheesepuffer** [MC-U-Team/Music-Player#248]
https://soundcloud.com/rareamericans/brittle-bones-nicky
https://soundcloud.com/rareamericans/brittle-bones-nicky-2-1
These songs and many others I have do not play. They have stopped playing for some reason.

**Comment by HyCraftHD** [comment]
Please send me the debug.log and the version of musicplayer you are using

**Comment by Cheesepuffer** [comment]
[debug-1.log.gz](https://github.com/MC-U-Team/Music-Player/files/6724826/debug-1.log.gz)

**Comment by HyCraftHD** [comment]
Seems to be caused by this change on soundclouds side here: https://github.com/sedmelluq/lavaplayer/issues/636

**Comment by HyCraftHD** [comment]
Need to wait for a fix on lavaplayers side

**Comment by HyCraftHD** [comment]
Should be fixed in these versions when they get approved: 
![image](https://user-images.githubusercontent.com/7681220/123869142-e9da7d80-d930-11eb-966c-d6ed13b1bb49.png)
