### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by mememasternate** [MC-U-Team/Music-Player#25]
**Describe the bug**
when i am using this mod i cant hear any audio in game is this a fault on my part if so how can i fix it
**To Reproduce**
1. Go to 'download the mod'
2. Do this 'and be in game'

**Expected behavior**

**Screenshots**

**Versions**
- minecraft version1.13.2
- Forge Version25.0.219
- UTeamCore Version 1.13.2-2.4.0.110

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
Hello,
I got a few reports of this issue some months ago. Turns out it was a very poor soundcard not supporting so many sound "channels" playing at the same time. If thats the case I cannot do anything about it.

The problem is I cannot reproduce this issue :/

**Comment by mememasternate** [comment]
is there any way i can fix this

**Comment by mememasternate** [comment]
if that is so would I not be able to run mc and Spotify and hear both?

**Comment by HyCraftHD** [comment]
Im not sure. I cannot investigate much in this bug as it is not reproducible for me. Do you have an updated pc? The sound card / onboard sound card is interesting.
