### ISSUE TITLE
[1.8.9] Crash on loading 

### ISSUE THREAD

**Issue by listingclown3** [MC-U-Team/Music-Player#254]
**Fail to launch to conflicting mods.**
Keep crashing on launch. Looked at errors, conflicting mods, anyway I can keep my mods along with music player?

**To Reproduce**
1. Have these mods, 
Dankers Skyblock Mod
AutoSprint-1.2.0
BetterFps-1.2.0
ctjs-1.3.1-1.8.9
Dungeon_Rooms-2.0.0
foamfix-0.6.3
NotEnoughUpdates-2.0-PRE26
Optifine_1.8.9_HD_U_L5
Patcher-1.5.1 (1.8.9)
Scrollable Tooltips-1.3
Skytils-0.3.1
(
  FMLLoadingPlugin (Dungeon_Rooms-2.0.0 (1).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  FMLLoadingPlugin (Skytils-0.3.1.jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  CTJSLoadingPlugin (ctjs-1.3.1-1.8.9.jar)
 )
  These are the mods that are conflicting

**Expected behavior**
To load but after trying multiple versions of the music player it still doesn't load. Crashes while loading up MC
![this](https://user-images.githubusercontent.com/86990758/124525851-a6ab5f00-ddb5-11eb-8cd9-242f6ecf1e2d.png)

Also I have the u-team thing. 
version for u-team: u_team_core-1.8.9-1.3.0.63

**Screenshots**

**Versions**
- Mod version: music_player-1.8.9-2.1.1.131
- Minecraft version: 1.8.9
- Forge version: 1.8.9 - 11.15.1.2318
- UTeamCore version: u_team_core-1.8.9-1.3.0.63

**Log (if crash occures)**
Link to crash log
[crash-2021-01-18_11.34.30-fml.txt](https://github.com/MC-U-Team/Music-Player/files/6766553/crash-2021-01-18_11.34.30-fml.txt)

**Comment by HyCraftHD** [comment]
Patcher is not compatible.

**Comment by HyCraftHD** [comment]
Should be fixed with this version https://www.curseforge.com/minecraft/mc-mods/music-player/files/3841508
