### ISSUE TITLE
[MC-Version] music doesn't play

### ISSUE THREAD

**Issue by memexyz123** [MC-U-Team/Music-Player#256]
music doesn't play no matter how long it takes

**Versions**
- Mod version: 2.3.2.140
- Minecraft version: 1.16.5
- Forge version: 36.1.32
- UTeamCore version: 3.2.1.196

**Comment by HyCraftHD** [comment]
What song (link) do you try to play?

**Comment by memexyz123** [comment]
bitch lasagna

**Comment by HyCraftHD** [comment]
Then please send me the link and the debug log when you tried to play it
