### ISSUE TITLE
[MC 1.12.2] GPU driver update broke Music Player?

### ISSUE THREAD

**Issue by ChielTheOread** [MC-U-Team/Music-Player#257]
So I had to update some of my drivers, and I updated my video drivers, and ever since then, music player doesn't work, when I play a song I hear nothing but the player says it's playing. I'm not sure what happened. 

- Mod version: 1.12.2 - 2.3.2.140
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2854
- UTeamCore version: 1.12.2 - 2.2.5.147

**Comment by HyCraftHD** [comment]
Well the " 2.3.2.140" version for 1.12.2 does not exist.
Which is the correct version?
Which song do you try to play (link please)
And please send me the debug log when you tried to play the song.

**Comment by ChielTheOread** [comment]
> Well the " 2.3.2.140" version for 1.12.2 does not exist.
> Which is the correct version?
> Which song do you try to play (link please)
> And please send me the debug log when you tried to play the song.

Wait, i don't know why i said 2.3.2.140, my bad
I meant version 1.12.2-2.1.1.137 of Music player

And Uteamcore version: 1.12.2-2.2.5.147

This is the first time I've sent a debug log, do i just drag and drop the entire folder? there's multiple files, or am I looking for a specific debug log? 

Sorry for the late response, I got no notification.

**Comment by HyCraftHD** [comment]
First run music player and try to play the song. (Still need the link!)
Then go to the logs directory and drag and drop the debug.log file in here

**Comment by ChielTheOread** [comment]
https://www.youtube.com/watch?v=DZ4vou_ZfQQ
Here's the song (But the song is a little irrelevant as i tried it on multiple random songs before this, so it's not a one-song thing)

Also sorry i'm not sure if i'm misunderstanding, i'm in the log folder but there's not "debug.log" or any log by that name, should I send my latest.log? or "2021-07-15-5" log?

**Comment by HyCraftHD** [comment]
then try the latest.log or the log that was created when you launched the game

**Comment by ChielTheOread** [comment]
> then try the latest.log or the log that was created when you launched the game

[latest.log](https://github.com/MC-U-Team/Music-Player/files/6831515/latest.log)
Here you go 
I should also note, this isn't on just one modpack, it seems to be across every instance of minecraft i've played recently, as i've been testing more than one modpack, and each time, since my GPU was updated, music player has no audio.

**Comment by HyCraftHD** [comment]
Alright, log seem okay. Can you try to go into the settings and change the audio output device in there? Maybe the graphics driver messed with the default one.

**Comment by ChielTheOread** [comment]
> Alright, log seem okay. Can you try to go into the settings and change the audio output device in there? Maybe the graphics driver messed with the default one.

Change in where? I'm not sure how to do that, if you mean music player settings, the most i can find is the stuff related to the GUI, and the config from the ingame menu which mentions "internal playlists" (which i tried turning that on, but it didn't change anything)

**Comment by HyCraftHD** [comment]
Oh you are right, in 1.12 there is no sound setting. Can you try that in 1.16.5 to see if that is the issue?

**Comment by ChielTheOread** [comment]
Alright, i booted up minecraft on 1.16.5 forge, with music player, not on the curseforge app, and music player works, and the ability to see audio output devices is there. Strange... 

I notice when I go to versions where I can select output, it's by default set on "primary sound driver", maybe it did change the default audio output like you mentioned? If so though, i'm not sure how to change it in 1.12.2

**Comment by ChielTheOread** [comment]
@HyCraftHD I think I figured out the issue, I apologize for all this. 

The issue was related to NVIDIA drivers. Incase anyone has the same issue as me again: Do not install the NVIDIA audio drivers when updating your GPU, it can have a lot of issues it seems, and one is messing up this mod.
