### ISSUE TITLE
[1.8.9] Minecraft crashes while having this mod in my folder

### ISSUE THREAD

**Issue by Maratons4** [MC-U-Team/Music-Player#268]
**Describe the bug**
Minecraft crashes while  

**Expected behavior**
Minecraft loading with the mod correctly

**Screenshots**
https://prnt.sc/1qg4xng

**Versions**
- Mod version: 2.1.1.136
- Minecraft version: 1.8.9
- Forge version: 11.15.2318-1.8.9
- UTeamCore version: 1.8.9-1.3.0.63

**Log (if crash occures)**
https://pastebin.com/guJqXNpS

**Comment by HyCraftHD** [comment]
See  #266 #254 #109 #63

**Comment by HyCraftHD** [comment]
Should be fixed with this version https://www.curseforge.com/minecraft/mc-mods/music-player/files/3841508
