### ISSUE TITLE
fabric port?

### ISSUE THREAD

**Issue by Diclo** [MC-U-Team/Music-Player#269]
a port for fabric would be interesting

**Comment by S-moreo** [comment]
i mean thats not really a bug XD

**Comment by MoonwalkDelta27** [comment]
I agree, most of the good client-side mods for 1.18 are Fabric-based

**Comment by HyCraftHD** [comment]
Ported for 1.18.2 and 1.19: See here: https://github.com/MC-U-Team/Music-Player-Fabric
![image](https://user-images.githubusercontent.com/7681220/174914391-88b688d4-6166-48ce-afe9-2fbc2b3097be.png)
https://www.curseforge.com/minecraft/mc-mods/music-player/files
