### ISSUE TITLE
[Question] Where does this mod tell MC/Forge to play the music?

### ISSUE THREAD

**Issue by alyxandraio** [MC-U-Team/Music-Player#270]
I have been searching the source code for about 45 minutes now and I can't find where this mod actually tells Minecraft (or Forge) to play the music. I've found the Lavaplayer stuff and the playlist management stuff but I can't find any Minecraft or Forge API calls for the music. Could you point me in the right direction? I'm looking to do something similar in a mod of mine.

**Comment by HyCraftHD** [comment]
The music isn't played through the minecraft sound engine. It's using the javax.sound api here: https://github.com/MC-U-Team/Music-Player/blob/6d9820e8d630458d479246faa8969ea2902b9503/musicplayer-lavaplayer/src/main/java/info/u_team/music_player/lavaplayer/output/AudioOutput.java#L55-L88

**Comment by alyxandraio** [comment]
Ah that makes sense, thank you very much! How does it stop playing Minecraft's BGM? I don't see anything that might do that there.

**Comment by HyCraftHD** [comment]
Well it just doesn't stop the background music of minecraft. The player needs to disable it themselves.

**Comment by alyxandraio** [comment]
I appreciate the help :)
