### ISSUE TITLE
[1.12.2] The Music Wont Play

### ISSUE THREAD

**Issue by R1ch4rdR4u** [MC-U-Team/Music-Player#271]
Hi My Name Is Richard But I Tried This Mod
Can You Fix What Happen The Audio Wont Play
Idk I Just See The Red Text Or The Audio Cant Play
I Play It And It Didnt Start :(
Please Fix The Issue

**Versions**
- Mod version: I Use The Lastest 1.12.2
- Minecraft version: 1.12.2 Pojav Launcher
- Forge version: 1.12.2
- UTeamCore version: Lastest 1.12.2

**Comment by R1ch4rdR4u** [comment]
I Tried 3 Houseki No Kuni Ost Wont Work

**Comment by HyCraftHD** [comment]
Please specify the versions. **Latest** does not mean anything.

Furthermore can you please attach the log and the url of the song that did not work?

**Comment by R1ch4rdR4u** [comment]
I mean I Tried Link Youtube Other Songs And Add Track After Go Back And Play Didnt Work

**Comment by R1ch4rdR4u** [comment]
![Screenshot_20211009_214411](https://user-images.githubusercontent.com/70051500/136660362-05519cea-2988-4310-bf8e-4a2b7a5e9010.jpg)
![Screenshot_20211009_214325](https://user-images.githubusercontent.com/70051500/136660371-77ef0d71-8ce6-4bbc-813f-9cc5dac727aa.jpg)
here the version

**Comment by R1ch4rdR4u** [comment]
That Minecraft Java Mobile Called Pojav Launcher

**Comment by HyCraftHD** [comment]
Alright, so you searched for the song in the musicplayer gui?Still need the log though please.

**Comment by R1ch4rdR4u** [comment]
I searched enough but is still wont play it look lemme screen shot it

**Comment by HyCraftHD** [comment]
What have you searched?

Please send the log. Without the log its not possible to diagnose the issue.

**Comment by HyCraftHD** [comment]
Closing because of lack of response. Please reopen if the issue still persists.
