### ISSUE TITLE
1.16.5 : Music occasionally cutting out during songs played both locally and from Youtube

### ISSUE THREAD

**Issue by Thrumptus** [MC-U-Team/Music-Player#273]
Every so often the music stops for about a second before resuming, originally i thought it was a Youtube thing but it still happens with local files

- Mod version: 2.3.2.140
- Minecraft version: 1.16.5
- Forge version: 36.2.8
- UTeamCore version: 3.2.1.196

**Comment by HyCraftHD** [comment]
This issue might be happening because your PC components.
What CPU does your PC has? How much RAM do you allocate for minecraft?

**Comment by Thrumptus** [comment]
> This issue might be happening because your PC components. What CPU does your PC has? How much RAM do you allocate for minecraft?

I have an AMD Ryzen 5 3600 6 core CPU with about 4gb of RAM allocated to Minecraft

**Comment by HyCraftHD** [comment]
Alright, that should definitely be enough to run music player smoothly.
An other guess might be because of the Garbage Collector of Java.

To get a better diagnose of that issue, the best you can do is, to run a Java Profiler and check when its lagging

**Comment by Thrumptus** [comment]
Will do, thanks for the help

**Comment by HyCraftHD** [comment]
Closing because of lack of response. Please reopen if the issue still persists.
