### ISSUE TITLE
Fabric Port

### ISSUE THREAD

**Issue by just-chubbyfoxx** [MC-U-Team/Music-Player#277]
It would be interesting to see, the mod has 700k+ downloads and there arent any mods similar to this whatsoever on fabric. You can catch a lot more downloads doing this, along with appease the people who use this mod.

**Comment by HyCraftHD** [comment]
You can check out the unofficial 1.17.1 fabric port here: https://github.com/Waterpicker/Music-Player
(Need to build it your self)

Maybe in 1.18 I might consider an official port, but don't quote me on that.

**Comment by HyCraftHD** [comment]
Duplicate of #269

**Comment by HyCraftHD** [comment]
Ported for 1.18.2 and 1.19: See here: https://github.com/MC-U-Team/Music-Player-Fabric
