### ISSUE TITLE
[MC-Version] Bug short description 

### ISSUE THREAD

**Issue by Mih21Santos** [MC-U-Team/Music-Player#278]
**Describe the bug**
hi don't have any bugs but i would appreciate it if you could put the new versions please don't scold me anymore i would like your mod created by MUSIC PLAY for 118.1 .thanks for your attention.

**Comment by HyCraftHD** [comment]
1.18.1 is published on curseforge now. Get it here https://www.curseforge.com/minecraft/mc-mods/music-player/files
