### ISSUE TITLE
[MC-Version] 

### ISSUE THREAD

**Issue by mynam333** [MC-U-Team/Music-Player#288]
### Bug description and reproduction steps

I can't add a playlist. Even if I try to add it, there is no input. The cursor does not blink with a left click, and the cursor is created only with a right click, but it has no effect. Please help me.

### Log files and Screenshots

![2022-01-08_02 43 37](https://user-images.githubusercontent.com/39339180/148584756-d21cd3aa-a346-4611-b811-b57017ab0bb2.png)
![2022-01-08_02 43 39](https://user-images.githubusercontent.com/39339180/148584762-8449d2f9-fc0c-4c40-b6dd-b527e950ba8d.png)

### Used minecraft version

1.12.x

### Used forge version

14.23.5.2860

### Used mod version

2.1.1.137

**Comment by HyCraftHD** [comment]
Do you have entered a playlist name in the textbox?

**Comment by mynam333** [comment]
I can't entered textbox.
It was not entered no matter how much I pressed the keyboard.

+ I add it because I think it will be helpful, the configuration GUI is displayed like this.

![2022-01-08_13 13 30](https://user-images.githubusercontent.com/39339180/148631041-5652b767-c504-43e5-9f85-bbad2559b43e.png)

**Comment by mynam333** [comment]
++ 다른 버전에서는 정상작동하지만 그곳에서 추가한 플레이리스트를 내가 이 버전에서 사용하려고 클릭하면 아무런 작동도 하지않는다.

**Comment by mynam333** [comment]
++ It works fine in other versions, but when I click on the playlist I added there to use in this version, nothing works.

**Comment by mynam333** [comment]
I thought it was a conflict between modes, and I deleted some modes. Then surprisingly, it worked. I'm sorry to surprise you all of a sudden.
