### ISSUE TITLE
[MC-1.16.5] Need a local music directory that can be imported.

### ISSUE THREAD

**Issue by JinXIOC** [MC-U-Team/Music-Player#291]
### Detailed description of the feature

Hello author, I think this module can add a local music directory or folder, which can facilitate me to manually import some downloaded music : ）

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
Hello, this feature does already exists in the import screen. You can select a single music file or load a whole directory with music
