### ISSUE TITLE
Here is what error appears, and here is the playlist itself

### ISSUE THREAD

**Issue by Niozor** [MC-U-Team/Music-Player#30]
https://drive.google.com/open?id=1Sd37kxYoRpZRgg5nt0mOF0ermbhMNHUz

https://drive.google.com/open?id=1WZZRCzdrEguGrowBLD4Mt8zE3YEH2wd4

**Comment by Niozor** [comment]
> https://drive.google.com/open?id=1Sd37kxYoRpZRgg5nt0mOF0ermbhMNHUz
> 
> https://drive.google.com/open?id=1WZZRCzdrEguGrowBLD4Mt8zE3YEH2wd4

Here is what error appears, and here is the playlist itself

**Comment by HyCraftHD** [comment]
Please use the issue template and provide me all necessary information.

**Comment by Niozor** [comment]
I'm sorry, I didn't understand what pattern?

**Comment by HyCraftHD** [comment]
If you click on open issue use the bug template and fill in and necessary information.

![grafik](https://user-images.githubusercontent.com/7681220/72178144-942faf80-33e2-11ea-892a-4f57624db6dd.png)
