### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by NekomusuMae** [MC-U-Team/Music-Player#301]
### Detailed description of the feature

Spotify support would be nice. I wasn't going to make this request but I can't find a mention of Spotify here, on the website, or on the mod page. Is there any specific reason to keep Spotify support out of the cards or has it simply not been requested yet.

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by yavko** [comment]
Maybe this could be done with librespot-java

**Comment by Omega172** [comment]
bump

**Comment by HyCraftHD** [comment]
See #992
