### ISSUE TITLE
Mod crashes when launched

### ISSUE THREAD

**Issue by ghost** [MC-U-Team/Music-Player#308]
### Bug description and reproduction steps

I have tried to launch Minecraft Forge 1.8.9 with this mod for that version along with the mod called uteamcore (Apparently its needed) minecraft crashes when I launch it with these mods. Is there any reason for this that I should be aware of or does the mod just not work because it's an older version?

Here's the error message if this helps:
<img width="504" alt="Screen Shot 2022-03-05 at 1 20 42 AM" src="https://user-images.githubusercontent.com/100977662/156858870-18c12709-7465-4a3b-b6fb-73307a40fb22.png">

### Log files and Screenshots

<img width="553" alt="Screen Shot 2022-03-05 at 1 24 47 AM" src="https://user-images.githubusercontent.com/100977662/156859075-05414fb7-0266-47ad-8711-bd654b0bcf62.png">

### Used minecraft version

1.8.x

### Used forge version

1.8.9-forge1.8.9-11.15.1.2318-1.8.9

### Used mod version

2.1.1.136

**Comment by HyCraftHD** [comment]
Known to be an issue with other mods for 1.8.9. Do you have the mod patcher installed?

**Comment by ghost** [comment]
Yes, I do.

**Comment by HyCraftHD** [comment]
Yes, thats the problem. Unfortunately no fix was found in a reasonable amount of time

**Comment by ghost** [comment]
Oh, should I uninstall patcher?

**Comment by HyCraftHD** [comment]
That's probably the only solution if you want to use music player for 1.8.9

**Comment by HyCraftHD** [comment]
Should be fixed in this version https://www.curseforge.com/minecraft/mc-mods/music-player/files/3841508
