### ISSUE TITLE
[1.12.2-1.15.1] Bug short description

### ISSUE THREAD

**Issue by Niozor** [MC-U-Team/Music-Player#31]
**Describe the bug**
I get this error when loading a playlist "The playlist file contains no links".

**To Reproduce**
1. I press F8
2. Then I click on Load file
3. I find a file with an extension .m3u
4. Click OK
5. And a red message appears "The playlist file contains no links"

**Expected behavior**
I thought that when I opened my playlist (which I created through the AIMP audio player) I would be able to listen to music in the game

**Screenshots**
https://drive.google.com/file/d/1Sd37kxYoRpZRgg5nt0mOF0ermbhMNHUz/view

**Versions**
- Minecraft Version 1.14.4
- Forge Version 1.14.4-forge-28.1.111
- UTeamCore Version 1.14.4-2.8.0.140

**Log (if crash occures)**
latest.log
https://drive.google.com/open?id=1qniG15CGJAqfn0CJ0Xe-jVqCSAlvaT0e
debug.log
https://drive.google.com/open?id=1acleIQ7M4Ixzshh7VU3jae6YHjnNvmJ5

**Comment by Vhenrique05** [comment]
1.12.2 version ?

**Comment by Niozor** [comment]
No I'm on 1.14.4

**Comment by HyCraftHD** [comment]
Thanks for the report. The version doesn't matter cuz the backend for loading the songs is the same.
I need to test that my self but I think I cannot do anything about that because I use lavaplayer as "music player"

**Comment by HyCraftHD** [comment]
Actuall I cannot do anything about this issue because lavaplayer only supports basic m3u playlists like these: https://www.ilovemusic.de/iloveradio.m3u
You may import your songs with add folder.

I'll close as there is no fix available
