### ISSUE TITLE
[MC-1.8.9] Soundcloud tracks won't play after relaunching minecraft

### ISSUE THREAD

**Issue by xrzi** [MC-U-Team/Music-Player#317]
### Bug description and reproduction steps

At first when you add music from soundcloud it plays just fine, but after closing minecraft and opening it again every sc track is marked "This url does not appear to be a playable track."

### Log files and Screenshots

Before reopening minecraft:
![image](https://user-images.githubusercontent.com/60040522/160988305-528b5c11-2aec-4d53-b764-8fffff3d7652.png)

After:
![image](https://user-images.githubusercontent.com/60040522/160988449-05b49d8a-3299-4a9a-9c27-1f4730e280b4.png)

latest.log entries, that appear to be relevant to this bug:
[relevant_log_entries.log](https://github.com/MC-U-Team/Music-Player/files/8386516/relevant_log_entries.log)
I will supply full log file if this is not enough

### Used minecraft version

1.8.x

### Used forge version

11.15.1.1764

### Used mod version

2.1.1.136

**Comment by HyCraftHD** [comment]
Should be fixed with these versions: 
![image](https://user-images.githubusercontent.com/7681220/162317689-6410f362-172e-488f-b41c-782c2326c288.png)
