### ISSUE TITLE
[1.18.2] 

### ISSUE THREAD

**Issue by Whitepaper77** [MC-U-Team/Music-Player#319]
### Bug description and reproduction steps

I cant listen to any YouTube songs.
Whenever I press a song I got from YouTube, it will be added to my playlist fine but as soon as I want to listen to it, the song will play for about 2 seconds with no audio then change to the next song.

### Log files and Screenshots

https://user-images.githubusercontent.com/103197652/162258455-8d12b239-c80a-4968-b9d8-e549bd2a21cd.mp4

### Used minecraft version

1.18.x

### Used forge version

40.0.19

### Used mod version

2.3.3.142

**Comment by HyCraftHD** [comment]
Hello, can you try to use [1.18.2-2.3.3.149](https://www.curseforge.com/minecraft/mc-mods/music-player/files/3739695) and see if that fixes your issue?

**Comment by HyCraftHD** [comment]
Closing as there is no response. Seems to be fixed. If the issue happens again. please reopen.
