### ISSUE TITLE
[1.15.2] Directories/files containing Japanese characters fail to load on playlists

### ISSUE THREAD

**Issue by RegularPerson** [MC-U-Team/Music-Player#33]
**Describe the bug**
Songs will play fine upon initial creation of the playlist, but when relaunching the game and attempting to play songs from the playlist, it cannot resolve the directory of the song files with Japanese.
**To Reproduce**
- Create a playlist with songs/directories containing Japanese characters (from Japanese albums and the like)
- Close and relaunch the game
- Enter the menu for Music Player and open the playlist 
- Songs containing Japanese characters will be labeled red with an error "no matches found" as all Japanese text will be replaced with '?'; Game will crash if you attempt to play them by clicking the skip button.
**Expected Behavior**
I'd hope the playlists would save properly with no issues locating and playing the songs. Current workaround is either to rename all songs/directories to English or to remake the playlist each time.
**Screenshots**
https://i.imgur.com/v4AQhmT.png
Result after reloading the game and opening the playlist containing the Japanese songs.
**Versions**
Minecraft 1.15.2
Forge 1.15.2-forge-31.0.1
U-Team Core 1.15.2-2.10.0.146
**Log**
crash-2020-01-30_22.55.18-client
https://pastebin.com/uHmCjMCB
latest.log
https://pastebin.com/ZvnHKZbu

**Comment by HyCraftHD** [comment]
Thank you for the report. Will investigate!

**Comment by HyCraftHD** [comment]
The issue is then encoding that is set to the vm. I'll use now utf-8 which supports japanese characers, as well as many other non english characters.
