### ISSUE TITLE
[1.12.2]

### ISSUE THREAD

**Issue by Atomlxe** [MC-U-Team/Music-Player#337]
### Bug description and reproduction steps

Opened my game, and it crashed once it loaded the mod. Mod list, crash log, and error code are below.

EDIT: Nevermind, I deleted the playlist and its fixed.

### Log files and Screenshots

[crash-2022-05-25_21.24.22-client.txt](https://github.com/MC-U-Team/Music-Player/files/8776287/crash-2022-05-25_21.24.22-client.txt)
![image](https://user-images.githubusercontent.com/100674380/170416542-a9dde685-d7eb-4215-ac1a-406d94c3d628.png)
![image](https://user-images.githubusercontent.com/100674380/170416649-9b4b654e-89f2-4977-8154-9c9ec5fb3717.png)

### Used minecraft version

1.12.x

### Used forge version

14.23.5.2859

### Used mod version

2.1.1.144

**Comment by HyCraftHD** [comment]
For others that encounter a similar issue. Delete the settings.json file in your %appdata%\mc-u-team\musicplayer directory.
