### ISSUE TITLE
[MC-Version] 1.18.2 forge optifine TLauncher

### ISSUE THREAD

**Issue by squarzyy** [MC-U-Team/Music-Player#343]
### Bug description and reproduction steps

it requires me at least FORGE 1.25, while I am FORGE 1.19 and i have download Uteam_core too, what should I do now, pls help

### Log files and Screenshots

I can take a picture because my prt SCR is not working

### Used minecraft version

1.18.x

### Used forge version

1.19

### Used mod version

1.18.2 1.0.6

**Comment by Fl414r** [comment]
maybe try download latest 1.18.2 forge?
https://files.minecraftforge.net/net/minecraftforge/forge/ 
if you need optifine just download it and place in mods folder...
https://optifine.net/downloads

**Comment by HyCraftHD** [comment]
Please do not use TLauncher.
