### ISSUE TITLE
MC 1.12.2 Youtube "no matching found"

### ISSUE THREAD

**Issue by Sanddino** [MC-U-Team/Music-Player#356]
### Bug description and reproduction steps

No Youtube search found using both the latest version of Uteamcore and Musicplayer as of April 2022 for MC 1.12.2. Soundcloud works fine.

### Log files and Screenshots

None. 

### Used minecraft version

1.12.x

### Used forge version

14.23.5.2854

### Used mod version

2.1.1.144

**Comment by HyCraftHD** [comment]
Should be fixed in these versions
![image](https://user-images.githubusercontent.com/7681220/174912895-17c32cd5-fadd-402a-8e79-d80a2978ba64.png)
