### ISSUE TITLE
[1.18.2] Pausing After Song Ends Using the Keybind Crashes

### ISSUE THREAD

**Issue by cam-reno** [MC-U-Team/Music-Player#386]
### Bug description and reproduction steps

1. Play Playlist
2. Wait For Playlist to end
3. Click Your "Pause" Keybind
4. Crash

### Log files and Screenshots

The game crashed whilst keypressed event handler
Error: java.lang.NullPointerException: Cannot invoke "info.u_team.music_player.lavaplayer.api.audio.IAudioTrack.getDuration()" because "currentlyPlaying" is null
Exit Code: -1

### Used minecraft version

1.18.x

### Used forge version

fabric-loader-0.14.8

### Used mod version

2.3.3.2

**Comment by HyCraftHD** [comment]
Please attach the whole crash log

**Comment by HyCraftHD** [comment]
Okay seems to be related to #387
