### ISSUE TITLE
does not work with new versions of uteamcores for 1.19

### ISSUE THREAD

**Issue by FudgeDumbo** [MC-U-Team/Music-Player#391]
### Bug description and reproduction steps

does not detect versions above 4.0.0.4

### Log files and Screenshots

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install uteamcore, version 4.0.0.4 or later.
Unmet dependency listing:
	 - Mod 'Music Player' (musicplayer) 2.4.0.5 requires version 4.0.0.4 or later of uteamcore, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

---------------------------------------------------------------------------------------
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install uteamcore, version 4.0.0.4 or later.
Unmet dependency listing:
	 - Mod 'Music Player' (musicplayer) 2.3.3.3 requires version 4.0.0.4 or later of uteamcore, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Used minecraft version

1.19.x

### Used forge version

fabric 0.14.8

### Used mod version

2.3.3.3 and 2.4.0.5

**Comment by 2el222** [comment]
Works fine for me tho... 
![image](https://user-images.githubusercontent.com/54117086/179372359-ce9e96ac-747d-40e0-868c-cc99229bfce3.png)
![image](https://user-images.githubusercontent.com/54117086/179372364-6da8d0f2-2738-49e6-be96-9ca95eff31e1.png)

**Comment by HyCraftHD** [comment]
You need to install uteamcore

**Comment by FudgeDumbo** [comment]
no it does not work.
I said above 4.0.0.4  which is uteamcore 4.0.0.4
It will not work with any new uteamcores.
you did not mention that in the mod page which I had to go thru the logs to find it out
and even the logs are not correct since it is saying "or later"
which made me to go thru almost all the versions above 4.0.0.4 and find out it only works with 4.0.0.4

**Comment by HyCraftHD** [comment]
Install this uteamcore version and it should work: https://www.curseforge.com/minecraft/mc-mods/u-team-core/files/3843175
You should just read the error.

**Comment by FudgeDumbo** [comment]
I am sorry? what does the error say?

- Mod 'Music Player' (musicplayer) 2.3.3.3 **requires version 4.0.0.4 or later of uteamcore,** **which is missing!**

what does the ticket title say?

does not work with new versions of uteamcores for 1.19 #391

what does the description say?

does not detect versions above 4.0.0.4


do you not understand english????

was that not clear enough you to understand the issue?

error says 4.0.0.4 or later

clearly it does not work with "later"

you should start learn how to read

**Comment by HyCraftHD** [comment]
It clearly works with the fabric version of uteamcore (4.0.0.4). It looks like you didn't even try to apply the suggested solution.
If you still have problems, open an issue with a **NEW** log, and don't be a dick!
