### ISSUE TITLE
[1.16.5] Music Player has failed to load correctly

### ISSUE THREAD

**Issue by TheJD17** [MC-U-Team/Music-Player#394]
### Bug description and reproduction steps

Upon initiating minecraft, it shows me an error that says: Cannot create extract directory for musicplayer files

### Log files and Screenshots

![imagen](https://user-images.githubusercontent.com/109884969/180629904-ce21a978-f201-41d4-a4f2-a714545b74c2.png)

### Used minecraft version

1.16.x

### Used forge version

36.2.35

### Used mod version

2.3.2.166

**Comment by HyCraftHD** [comment]
Okay that should not happen. Can you please upload the log file of the crash?

**Comment by TheJD17** [comment]
Sure. 
[crash-2022-07-23_21.21.36-fml.txt](https://github.com/MC-U-Team/Music-Player/files/9221939/crash-2022-07-23_21.21.36-fml.txt)

**Comment by HyCraftHD** [comment]
Your temp directory is set to C:\WINDOWS\TEMP which is not writable by java. Really weird. Can you open the command promt and enter ``echo %TEMP%``?
