### ISSUE TITLE
It clearly works with the fabric version of uteamcore (4.0.0.4). It looks like you didn't even try to apply the suggested solution.

### ISSUE THREAD

**Issue by FudgeDumbo** [MC-U-Team/Music-Player#395]
It clearly works with the fabric version of uteamcore (4.0.0.4). It looks like you didn't even try to apply the suggested solution.
If you still have problems, open an issue with a **NEW** log, and don't be a dick!

_Originally posted by @HyCraftHD in https://github.com/MC-U-Team/Music-Player/issues/391#issuecomment-1193843045_

**Comment by FudgeDumbo** [comment]
clearly you don't read what the issue is about.
I did not say 4.0.0.4 was not working, you moron.
I clearly mentioned that "new" uteamcores are not working with your stupid shitty mod.
and mod page does not mention about it also the error message is miss lead.
guess what people will be downloading, when you only mention uteamcore required? new versions.
guess what people will be using, when error message says 4.0.0.4 or later? new versions.
I posted the issue to help you guys with the mod and you are just being so ignorant and dumb.
who is being a dick and ignorant?
do you even read what I have posted? do you even have a brain to process before what you say?
check how and what you have replied.
It is just stupid to see a mod being so dumb and no brain.

**Comment by HyCraftHD** [comment]
🤡
Maybe there is a difference between forge and fabric you didn't know about? LMFAO!
