### ISSUE TITLE
Suggestion: Parties

### ISSUE THREAD

**Issue by Jkosio23** [MC-U-Team/Music-Player#4]
"An Idea: Make a "Party Mode"... Players can be added to party to hear the same song together. With permissions like "DJ", that allows you to put musics in Queue. it will be a nice addition to this amazing mod! :D"
Not my idea but I support it, it was left as a comment on the minecraft curseforge page by makzzin1.

**Comment by HyCraftHD** [comment]
Noted it down, but currently i dont have time to work on this project

**Comment by HyCraftHD** [comment]
Won't be implemented because i decided this mod should stay clientsided.
