### ISSUE TITLE
[1.12.2] Feature Suggestion

### ISSUE THREAD

**Issue by TheGiantBean** [MC-U-Team/Music-Player#40]
It would be amazing instead of having the music just for your self if you can play it for your friends too using the jukebox. That is all thanks!

**Comment by HyCraftHD** [comment]
An option to stream the music to other players will be released soon as an addon with my new voicechat mod.
However this mod will only be released for 1.15.2 and not be backported.

**Comment by HyCraftHD** [comment]
Is implemented with the voicechat mod since 1.15.2
