### ISSUE TITLE
[MC-Version] use old Version mod

### ISSUE THREAD

**Issue by whycantiusemyname** [MC-U-Team/Music-Player#41]
i want to use this mod on 1.8.9. and when i download the latest version of the mod and U-Team-Core,but i get crash. so which ver should i use?

**Comment by whycantiusemyname** [comment]
use mod:  music_player-1.8.9-2.0.3.55 u_team_core-1.8.9-1.3.0.63

**Comment by HyCraftHD** [comment]
Please fill in the template. It is there for a reason!
1.8.9 do not need uteamcore. Just use Music-Player-1.8.9-2.0.3.55 and it should work.
If not open an other issue and fill in the whole template with linked crash report.
