### ISSUE TITLE
[1.15.2] Music skips youtube songs

### ISSUE THREAD

**Issue by SwanX1** [MC-U-Team/Music-Player#42]
**Describe the bug**
Some songs don't play and throw an error in lavaplayer.

**To Reproduce**
Literally trying to play [DripReport - Sketchers](https://www.youtube.com/watch?v=LxyDknaCpq8) doesn't work.

**Versions**
- Mod version: 2.0.7.59
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2831
- UTeamCore version: 2.2.5.147

**Log (if crash occures)**
No crash, but console reads:
`[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:318]: [lava-daemon-pool-playback-1-thread-2] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of LxyDknaCpq8
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:319]: 	at java.lang.Thread.run(Unknown Source)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: Caused by: java.io.IOException: Received non-success response code 404
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
[lava-daemon-pool-playback-1-thread-2/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:325]: 	... 4 more`

**Comment by HyCraftHD** [comment]
Thanks for the report. Seems like youtube changed something. Need to updata lavaplayer

**Comment by HyCraftHD** [comment]
Fixed in the latest builds for 1.12.2, 1.14.4 and 1.15.2
