### ISSUE TITLE
[MC-Version] Error with youtube links

### ISSUE THREAD

**Issue by Red1004** [MC-U-Team/Music-Player#420]
### Bug description and reproduction steps

Youtube links don't load and display "Loading information for a YouTube track failed." I've tested and it works fine on the 2.2.1.156 version, just not on 2.2.1.165.

### Log files and Screenshots

![image](https://user-images.githubusercontent.com/111118837/184325446-c7021b33-ad85-4ddb-bb69-2b8a37fcf5f2.png)

### Used minecraft version

1.15.x

### Used forge version

31.2.57

### Used mod version

2.2.1.165

**Comment by HyCraftHD** [comment]
Working on a fix. Youtube changed something.

**Comment by HyCraftHD** [comment]
Fixed in these versions: 
![image](https://user-images.githubusercontent.com/7681220/184344711-3eae4c33-cf77-4145-ae52-cbd3a013d6b9.png)
