### ISSUE TITLE
[1.18.2] music not working

### ISSUE THREAD

**Issue by BLAZINGKAT** [MC-U-Team/Music-Player#422]
### Bug description and reproduction steps

do not know how to recreate but YouTube songs wont load but other sources work fine

### Log files and Screenshots

don't have screen shots or crash reports

### Used minecraft version

1.18.x

### Used forge version

1.18.2-forge-40.1.73

### Used mod version

music_player-1.18.2-2.3.4.167

**Comment by BLAZINGKAT** [comment]
fixed it just had to delete both uteamcore and music player then boot Minecraft close it then reinstall both mods and it works again

**Comment by BLAZINGKAT** [comment]
can someone set this as resolved and close it thx

**Comment by HyCraftHD** [comment]
For others: Update to the latest versions. They should work for now.
![image](https://user-images.githubusercontent.com/7681220/184509158-314b29d7-6149-4ec0-90d2-b2a52d97b376.png)
