### ISSUE TITLE
[1.18.2] Song skipping when song not loading instantly

### ISSUE THREAD

**Issue by Catomax262** [MC-U-Team/Music-Player#424]
### Bug description and reproduction steps

1. Insert any YT playlist (single entry) into a Music Player entry.
2. Play any of the songs inside.
3. Wait for it to load and play (intended)
4. If it doesn't load, it will skip to the song below.
It seems to skip faster with low internet speed. Also, it may cause a chain reaction where, when it doesn't load, it skips to the song below, and if that song doesn't load then the same thing goes on and on.

### Log files and Screenshots

n/a

### Used minecraft version

1.18.x

### Used forge version

40.1.60

### Used mod version

2.3.4.167

**Comment by HyCraftHD** [comment]
Should be fixed in the latest versions
