### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by farlessthanhuman2014** [MC-U-Team/Music-Player#43]
**Describe the bug**
some songs would stop as soon as they started.
**To Reproduce**
2. Do this '....'

**Expected behavior**

**Screenshots**

**Versions**
- Mod version: xxx
- Minecraft version: xxx
- Forge version: xxx
- UTeamCore version: xxx

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
Fill in the whole issue template
