### ISSUE TITLE
[MC-Version] 

### ISSUE THREAD

**Issue by ElderHush** [MC-U-Team/Music-Player#447]
### Bug description and reproduction steps

Loading youtube or soundcloud songs.
-Youtube will insta-skip
-Souncloud will play for a short period of time and stop (max 30 seconds)

-version: music_player-1.19.1-2.5.1.170 (1.19.1)

### Log files and Screenshots

N/A

### Used minecraft version

1.19.x

### Used forge version

1.19.1

### Used mod version

2.5.1.170

**Comment by HyCraftHD** [comment]
Update to 1.19.2
