### ISSUE TITLE
The songs are shuffling except it doesnt stop or plays the musik

### ISSUE THREAD

**Issue by Otzlotz** [MC-U-Team/Music-Player#45]
Maybe it has something to do with the hatchery mod .

The bug occured after I added the hatchery mod to my Minecraft Modpack.

But after I removed it it was still there.

**Versions**
- Mod version: Music-Player-1.12.2-2.0.7.59
- Minecraft version: 1.12.2
- Forge version:  forge-14.23.5.2838
- UTeamCore version: U-Team-Core-1.12.2-2.2.5.147

I cant Show a screenshot because it would Need a Video to see the Problem.

It  didn't crash.

**Comment by HyCraftHD** [comment]
Update to the latest music player version for 1.12.2

**Comment by Otzlotz** [comment]
still there

**Comment by Otzlotz** [comment]
i can send you a Video per mail or dropbox if u want

**Comment by HyCraftHD** [comment]
Which song? Which music player version?

**Comment by Otzlotz** [comment]
or any other source

**Comment by Otzlotz** [comment]
there are 3 Playlists

**Comment by HyCraftHD** [comment]
Just send me the link to the errored song. Also I asked you about the versions used.

**Comment by Otzlotz** [comment]
and the Version is Music-Player-1.12.2-2.0.7.6 from 10.4.

**Comment by HyCraftHD** [comment]
Then please the link

**Comment by Otzlotz** [comment]
https://www.youtube.com/playlist?list=PLNxOe-buLm6cz8UQ-hyG1nm3RTNBUBv3K
https://www.youtube.com/playlist?list=PLbTCtOnWXbmiBWQ3S_0jXHm8GagjOF6F9
https://www.youtube.com/playlist?list=PL4t-k4YMDXtLSpY3x-NEeT6_gjVXI__VP
thats all

**Comment by Otzlotz** [comment]
lets continue tomorrow

**Comment by HyCraftHD** [comment]
Tested it with 1.12.2-2.0.7.64 and all 3 playlists worked. Have you really updated to this version?

**Comment by Otzlotz** [comment]
Yes i did.

**Comment by HyCraftHD** [comment]
So it works now?

**Comment by Otzlotz** [comment]
Unfortunately Not.

**Comment by Otzlotz** [comment]
I fixed it

**Comment by Otzlotz** [comment]
Just reinstall the mod.
