### ISSUE TITLE
Instant skips

### ISSUE THREAD

**Issue by Cleverflame6778** [MC-U-Team/Music-Player#48]
**Describe the bug**
When I go to play a song in 1.15.2 the song immediately skips and I cant hear any music

**Expected behavior**
I expected the song to play as the mod description states

**Versions**
- Mod version: 2.0.14.73
- Minecraft version: 1.15.2
- Forge version: 31.1.12
- UTeamCore version: 2.11.0.156

**Comment by HyCraftHD** [comment]
Which remote source is the song from? Youtube, Soundcloud, Http or Local?
Can you send the link to the song thats now working?

**Comment by MrProton657** [comment]
I have the same Issue, yesterday then I added the mod to my 1.12.2 private modpack everything worked fine, but today it dont work, I tried several versions of the coremod and the musicplayer mod itself on a clean Vanilla minecraft instance 1.12.2 with only forge and the mod and the core mod installed, tried differend tracks and it didnt work, it keeps skipping (I am using Youtube only.)
here some playlists I tryed: 

https://www.youtube.com/watch?v=zk801cz8CHE&list=PLD_CsXBE0-IglzP6FqD20fshYofkqpQmo&index=4

https://www.youtube.com/watch?v=RFH4VB-a6p4&list=PL9uU7rUTotvvo1_43N388RCdjwY01cTRw&index=28

https://www.youtube.com/watch?v=ymXOg_x96g8&list=PLFCB898C212100F6A
pls fix this quick

**Comment by HyCraftHD** [comment]
@MrProton657 Which are the exact versions you used?
Tested them all and they all worked on these versions:
- 1.12.2-2.0.8.71
- 1.14.4-2.0.10.72 
- 1.15.2-2.0.14.73

**Comment by MrProton657** [comment]
u_team_core-1.12.2-1.3.0.72
v1.1.1
v1.0.0
2.2.4.107
2.2.5.147
2.2.4.133
music_player-1.12.2-2.0.8.71
2.0.7.59
2.0.5.49
2.0.0.9
1.0.0-2
2.0.3.39

**Comment by HyCraftHD** [comment]
@MrProton657 These are all old versions. Please update to the latest version! There are updates for a reason!

**Comment by MrProton657** [comment]
I know, I tried older versions, after the latest even the first because why not

**Comment by MrProton657** [comment]
I will try it now an another time

**Comment by HyCraftHD** [comment]
Just use the 1.12.2-2.0.8.71 and it should work. It will break eventually, when youtube changes their format again. This mod relies on lavaplayer and that awesome library needs to update when youtube / soundcloud changes their formats. Thats why this mod sometimes needs updates and old versions are likely broken.

**Comment by MrProton657** [comment]
Whitch U TEam core version should I use? 1.12.2-2.2.5.147?

**Comment by HyCraftHD** [comment]
The latest. The music player mod says if the version is outdated

**Comment by MrProton657** [comment]
it doesnt work: https://www.youtube.com/watch?v=s6h9sSHckio

**Comment by HyCraftHD** [comment]
Do other youtube videos work? Are these videos available on the website in your country? Can you send me the log?

**Comment by MrProton657** [comment]
Yesterday everything worked fine, today it doesnt work anymore, I havent changed anything with your mods, the youtube videos themself work in youtube, what log do you mean, where is it?

**Comment by HyCraftHD** [comment]
The log of minecraft. Its under logs/debug.log or logs/latest.log or logs/fml-debug etc

**Comment by MrProton657** [comment]
[latest.log](https://github.com/MC-U-Team/Music-Player/files/4567881/latest.log)

**Comment by HyCraftHD** [comment]
Your ip is rate limited by youtube.
If you have a dynamic ip address from your provider a simple router restart should fix that.

**Comment by MrProton657** [comment]
ok, I'll try now

**Comment by MrProton657** [comment]
Ok I fixed it thank you very much! I wanted to say that I love your mod, youre were right it was the ip, but then I restarted the router it didnt helped, and I know I have a dynamic IP, but now I tried to use a VPN, and it WORKS!

**Comment by MrProton657** [comment]
Übrigens kann ich auch deutsch und wohne in Berlin, hab gerade gesehen bei Github das du aus Deutschland kommst ^^

**Comment by HyCraftHD** [comment]
Cool!
Sehr schön das es jetzt bei dir funktioniert!

**Comment by HyCraftHD** [comment]
As there is no response from the origin author I'll close. Please reopen if the issue persists.
