### ISSUE TITLE
Suggestion: Save radio stream urls so we can switch between them without needing to re-paste urls

### ISSUE THREAD

**Issue by tobi-polar** [MC-U-Team/Music-Player#5]

**Comment by HyCraftHD** [comment]
Im currently rewriting most of the project for 1.13.2. I'll add playlists and stuff like that. Might backport it to 1.12 too.

**Comment by HyCraftHD** [comment]
This is implemented for versions 2.0.0 for Minecraft 1.12.2 and 1.13.2.
For downloads see: https://minecraft.curseforge.com/projects/music-player/files
