### ISSUE TITLE
[1.12.2] Suggestion for Youtube Playlist compatibility?

### ISSUE THREAD

**Issue by Geezt435** [MC-U-Team/Music-Player#50]
Can you made it so I can load my youtube playlist instead of one by one? it's a tiring process since because when I open the music via link in the playlist, it has different URL

**Comment by HyCraftHD** [comment]
That is already implemented. Just pase the youtube playlist link and click add all or the first list item to add the whole playlist

**Comment by Geezt435** [comment]
Nope, still can't insert youtube playlist
![Screenshot (102)](https://user-images.githubusercontent.com/46617557/81545966-43d65780-93ac-11ea-8c22-13f62632597e.png)
![Screenshot (103)](https://user-images.githubusercontent.com/46617557/81545973-4769de80-93ac-11ea-8291-b3b4fd9ec502.png)

**Comment by HyCraftHD** [comment]
You must use the enter url to track field.

**Comment by Geezt435** [comment]
Same result 
![Screenshot (104)](https://user-images.githubusercontent.com/46617557/81546149-86982f80-93ac-11ea-9928-b062d9a07896.png)
![Screenshot (103)](https://user-images.githubusercontent.com/46617557/81546163-8b5ce380-93ac-11ea-81a5-44958e605421.png)

**Comment by HyCraftHD** [comment]
Insert in the textbox and hit enter. Then klick add all.

**Comment by Geezt435** [comment]
Both URL line filled
![Screenshot (105)](https://user-images.githubusercontent.com/46617557/81546400-e42c7c00-93ac-11ea-903f-d877834c8dd7.png)
Results in same
![Screenshot (106)](https://user-images.githubusercontent.com/46617557/81546414-ea225d00-93ac-11ea-9f03-b881a73d449a.png)

**Comment by HyCraftHD** [comment]
You are not pressing enter, are you? If you pressed enter and still nothing appears, please send me you debug log

**Comment by Geezt435** [comment]
Oh wait, I noticed I have keybind that have enter, now it works when I move the keybind to non enter
