### ISSUE TITLE
[1.8.9] Some songs just not playing in general.

### ISSUE THREAD

**Issue by Yoshi24517** [MC-U-Team/Music-Player#52]
**Describe the bug**
I click on a song, and hit play, and nothing happens.

Looking in logs, it looks like the player has issues trying to read certain YouTube songs/videos.

**To Reproduce**
These songs I know I was having trouble with:
https://www.youtube.com/watch?v=f3MDGKw0wdg
https://www.youtube.com/watch?v=Q5gO7Uvw3BU
https://www.youtube.com/watch?v=0Wi8Fv0AJA4

Basically just add them to a playlist and start the player.

**Expected behavior**
Song should NOT play, and should just be stuck at 00:00.

**Screenshots**
N/A

**Versions**
- Mod version: 2.0.3.55
- Minecraft version: 1.8.9
- Forge version: 1.8.9 (Forge version 11.15.1.1722)
- UTeamCore version: 1.8.9 (Version v1.1.2-51)

**Log (if crash occurs)**
Not a crash log, but here is a pastebin of my latest.log: https://pastebin.com/LNVi5F0T

- See starting from line 2727 onwards.
- Note: At line 178 it tells me I have an outdated version, 2.0.3.55 was the latest I could find for 1.8.9.
- Also, at line 229 it looks like uteamcore throws an error of http code 405. Not sure if that is related.

Thanks!

**Comment by HyCraftHD** [comment]
H̶e̶l̶l̶o̶,̶ ̶t̶h̶a̶n̶k̶s̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶r̶e̶p̶o̶r̶t̶.̶ ̶C̶a̶n̶ ̶y̶o̶u̶ ̶r̶e̶m̶o̶v̶e̶ ̶u̶t̶e̶a̶m̶c̶o̶r̶e̶ ̶p̶l̶e̶a̶s̶e̶ ̶a̶s̶ ̶t̶h̶i̶s̶ ̶m̶o̶d̶ ̶i̶s̶ ̶n̶o̶t̶ ̶r̶e̶q̶u̶i̶r̶e̶d̶ ̶f̶o̶r̶ ̶1̶.̶8̶ ̶v̶e̶r̶s̶i̶o̶n̶s̶ ̶o̶f̶ ̶m̶u̶s̶i̶c̶ ̶p̶l̶a̶y̶e̶r̶.̶ ̶I̶t̶ ̶j̶u̶s̶t̶ ̶t̶h̶r̶o̶w̶s̶ ̶m̶a̶n̶y̶ ̶e̶r̶r̶o̶r̶s̶.̶ ̶C̶a̶n̶ ̶y̶o̶u̶ ̶t̶h̶e̶n̶ ̶r̶e̶s̶e̶n̶d̶ ̶t̶h̶e̶ ̶l̶o̶g̶ ̶p̶l̶e̶a̶s̶e̶.̶

Oh just noticed. You are using an old versions of music player. Please update to the latest version 2.0.3.70

**Comment by Yoshi24517** [comment]
I could not find an 2.0.3.70 for 1.8.9. I put it as a comment above in my original report.

EDIT: Oh just kidding, I just can't read. Found it, will report back if it fixed it.

**Comment by Yoshi24517** [comment]
Fixed the issue, will reopen if it occurs again. Thanks for the hint, lol.

**Comment by Yoshi24517** [comment]
Reopening as I said, as problem is now reoccurring.

Same MC version, same Forge version, same UTeam Core version.
Using latest music player (2.0.3.70).

Unfortunately, it is happening again with this one: https://www.youtube.com/watch?v=Qt9dTkDIlH0

New log: https://pastebin.com/00zXFYzg
Start at line 2759.

Looks like a different error this time.

**Comment by HyCraftHD** [comment]
Seems like youtube changed their api, and I'll need to update lavaplayer.

**Comment by HyCraftHD** [comment]
#53 for discussion

**Comment by HyCraftHD** [comment]
Fixed with the latest update
