### ISSUE TITLE
[1.8-1.15.2] songs being skipped

### ISSUE THREAD

**Issue by LithTheKitten** [MC-U-Team/Music-Player#53]
**Describe the bug**
some songs wont even play, the thing just skips it automatically, it plays other songs but not these ones.
i think it has something to do with the VEVO or official publishers.

**To Reproduce**
1. Go to https://www.youtube.com/watch?v=zvq9r6R6QAY
https://www.youtube.com/watch?v=dQw4w9WgXcQ
https://www.youtube.com/watch?v=fNFzfwLM72c
https://www.youtube.com/watch?v=jU6kU2d0MbU

2. play them**Expected behavior**

it gets auto skipped.

**Screenshots**
none

**Versions**
- Mod version: 1.12.2
- Minecraft version: 1.12.2
- Forge version: forge1.12.2-14.23.5.2847
- UTeamCore version: ?? as of February 2020, latest 1.12.2 file

**Log (if crash occures)**
Link to crash log

**Comment by LithTheKitten** [comment]
soundcloud doesnt do this, and if you repeatetly click the play button it eventually plays, but it really just doesnt want to play these songs and others for some dumb reason

**Comment by Antman4** [comment]
i have a similar problem, but any song 3 min or over is skipped, but any song that was under 3 min did not work. i was using youtube urls though, i have not tried sound cloud though. so the problem might lie in the time stamp, not nessicarily copyright issues

**Comment by dxrthvxder** [comment]
Yeah, this happens to me, so I just use SoundCloud. However, when you look up some songs, it says "something went wrong while looking up the track", and I do not know how to fix this. Most songs work though.

**Comment by Yoshi24517** [comment]
By mod version, meaning what version of the mod. For example, the latest 1.8.9 version is 2.0.3.70. They mean the latest version of the 1.12.2 mod.

**Comment by LithTheKitten** [comment]
U-Team-Core-1.12.2-2.2.5.147
Music-Player-1.12.2-2.0.8.71
Forge version: forge1.12.2-14.23.5.2847
should i just reinstall, maybe the mod is corrupted. i do have a lot of mods but they are just to add more mobs in.

**Comment by HyCraftHD** [comment]
Thank you all for the reports. Need to verify that soon.
Seems like youtube changed their api, and I'll need to update lavaplayer.

**Comment by LithTheKitten** [comment]
that some kind of security thing?

**Comment by HyCraftHD** [comment]
No, there were some cipher detection issues because youtube changed something. I updated lavaplayer and it should work for all versions now again! Please update to the latest version
