### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by FrederickTheStormer** [MC-U-Team/Music-Player#557]
### Bug description and reproduction steps

Whenever I try to use Music Player it stutters.

### Log files and Screenshots

Stuttering

### Used minecraft version

1.16.x

### Used forge version

36.2.34

### Used mod version

2.3.2.183

**Comment by HyCraftHD** [comment]
What hardware do you use the mod on? How good is your internet connection? What songs did you use?

**Comment by HyCraftHD** [comment]
Closing because no response. If the issue still persists, please reopen
