### ISSUE TITLE
[1.15.2] Playing music on mac crashes the game

### ISSUE THREAD

**Issue by SeliliPona** [MC-U-Team/Music-Player#56]
That's really all. I didn't get a crash report but I did get a pop-up saying to send something to Apple. I'll update this if I get anything new.

**Comment by imaidenB666** [comment]
I also accidentally trapped myself out of the music player. F8 doesn't work. Help?

**Comment by HyCraftHD** [comment]
Without a log I cannot help you. Your description seems like it isn't even a minecraft issue. Please fill in the whole issue template and try to get a log. If you still get none please try to reinstall minecraft, forge and this mod

**Comment by HyCraftHD** [comment]
Closing as the is so response. If the issue still persists please open a new issue.
