### ISSUE TITLE
[1.8.9] game cant load sometimes if use Music Player and Patcher same time

### ISSUE THREAD

**Issue by Fl414r** [MC-U-Team/Music-Player#560]
### Bug description and reproduction steps

idk just load Patcher and Music Player in same time

### Log files and Screenshots
(all attempts with UTeamcore)
1) Music Player and Patcher after PC restarted (Freeze on UTeamcore Initialization Stage)
[latest111.log](https://github.com/MC-U-Team/Music-Player/files/10387284/latest111.log)
2) Only Music Player first load after remove Patcher (same freeze)
[latest222.log](https://github.com/MC-U-Team/Music-Player/files/10387285/latest222.log)
3) Only Music Player second load (all ok)
[latest333.log](https://github.com/MC-U-Team/Music-Player/files/10387287/latest333.log)
4) Music Player and Patcher after 2 and 3 (all ok)
[latest444.log](https://github.com/MC-U-Team/Music-Player/files/10387283/latest444.log)

### Used minecraft version

1.8.x

### Used forge version

11.15.1.2318

### Used mod version

2.1.1.188 and 2.1.1.179 (nothing change)

**Comment by Fl414r** [comment]
#63

**Comment by HyCraftHD** [comment]
Hm okay, can you remove uteamcore. Its not needed for 1.8.9.
For the other runs I'll have a look next week

**Comment by Fl414r** [comment]
> Hm okay, can you remove uteamcore. Its not needed for 1.8.9.

Maybe add this to the Curseforge page? (I mean, the minimal version with which UTeamcore is required)

**Comment by Fl414r** [comment]
It still active? Oops
