### ISSUE TITLE
[1.19.3] Play Audio through Command

### ISSUE THREAD

**Issue by greglor** [MC-U-Team/Music-Player#562]
### Detailed description of the feature

A command that can be used in singleplayer or servers that will play a song directly from a url, or from a playlist already made in a specified player's "jukebox".

The command should play the audio to all targeted players and be able to be looped.

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by banan4phon3** [comment]
totally agree. commands like: play, pause, stop, next, previous would be very usefull for all datapack and mod creators. this way they could use, for instance, their favourit boss themes, without running into to copyright issues.
