### ISSUE TITLE
[1.12.2] Youtube search always failing in version 2.0.8.77

### ISSUE THREAD

**Issue by Darkmega18** [MC-U-Team/Music-Player#59]
**Describe the bug**
Whenever I search for music on youtube like I used to be able to, it will always say nothing found. Soundcloud works fine. Nothing shows up on the console.

**To Reproduce**
just search for music in youtube search mode. not sure what could be blocking it or if something changed over on youtube making it stop working.

**Versions**
- Mod version: 2.0.8.77
- Minecraft version: 1.12.2
- Forge version: 1.12.2. ends in 2854
- UTeamCore version: 2.2.5.147

**Comment by HyCraftHD** [comment]
Hello, thanks for the report. Seems like youtube changed something. Music player currently ships with lavaplayer version 1.3.49
https://github.com/sedmelluq/lavaplayer/blob/master/CHANGELOG.md#1350----2020-06-17
In 1.3.50 they fixed the problem, so i will update the mod when I have time. Expect it in a week or so.

In the meantime you can create a playlist on youtube and just import the whole playlist

**Comment by Darkmega18** [comment]
oh, importing a playlist off youtube is a thing? will do, if I need to go that far. but I got some good enough songs in my ingame playlists to keep me for a bit. good luck with the fixing. atleast it's not my pack getting too chunky. lol

**Comment by LithTheKitten** [comment]
you can just use the url locater, it works at least, for me it did

soundcloud works fine as well, youtube has issues doe

**Comment by StarLight20001** [comment]
Hello, I have the same version and the same thing happens to me only that it does not reproduce, it does not save local files or search for URL's (either from YouTube or Soundcloud) basically, the mod is unused :(
Thanks for your attention.

**Comment by HyCraftHD** [comment]
As I said use direct links or a playlist link. Currently that is a workaround as I have not time to fix the issue currently

**Comment by HyCraftHD** [comment]
Use these versions now. They should work:
![grafik](https://user-images.githubusercontent.com/7681220/88298427-703e1680-cd01-11ea-988e-9faab9239d16.png)

**Comment by Darkmega18** [comment]
thanks muchly. will download when I next use my packs. :)
