### ISSUE TITLE
[MC-Version] refresh button?

### ISSUE THREAD

**Issue by LithTheKitten** [MC-U-Team/Music-Player#61]
**Describe the bug**
certain songs keep popping up as 
"Received an unexpected response from Youtube."
it becomes unplayable. it fixes itself when minecraft is completely restarted but then some other song will just have the error

you have to find the video and just redownload it into the list
maybe some kind of refresh link button for this?
if it helps its only seem to happen in one file that has 51 songs in it
maybe too many links in one single file to keep track of?

**To Reproduce**
just load up a file and check if a song in the list failed to pop up

**Expected behavior**
unexpected response

**Screenshots**

**Versions**
- Mod version: 1.16.3
- Minecraft version: 1.16.3
- Forge version: 34.1.0
- UTeamCore version: 1.16.3

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
Youtube is currently kinda buggy with musicplayer right now. I need to wait for lavaplayer to fix this.

**Comment by HyCraftHD** [comment]
This issue should have been fixed with these versions: 
![Foo](https://cdn.discordapp.com/attachments/760615360239108147/767185223312998420/unknown.png)
https://www.curseforge.com/minecraft/mc-mods/music-player/files

**Comment by LithTheKitten** [comment]
epic thx
