### ISSUE TITLE
[MC-Version] adding a playlist 

### ISSUE THREAD

**Issue by strike200** [MC-U-Team/Music-Player#62]
Used the latest mod and uteam core versions for 1.12.2
music_player-1.12.2-2.1.0.85
u_team_core-1.12.2-2.2.5.147

In my case it crashes while trying to play a playlist url on youtube. 
Used to work before.
Individual video/url works, but its too much of a hustle to add 600 urls.
Re-adding the playlist url does not fix the issue.
In case its not clear the game loads successfully to the main menu and even loads a save/world, the crash accures only when trying to play or add a playlist.
I'd be cool if someone could look up in the crash report, if its a problem on my end or in the mod in general, what may be the cause and if its even possible to fix.

[crash-2020-09-29_23.30.42-client.txt](https://github.com/MC-U-Team/Music-Player/files/5301683/crash-2020-09-29_23.30.42-client.txt)

Tried it with and without the rest of the mods i usually use in both cases it crashes. 
Used only "music player" and "u team core" in the crash report here.

Could be something youtube did with the way playlists work. The said play list is public and i tried using others shorter (4 videos) or longer ones.

**Comment by HyCraftHD** [comment]
This issue should have been fixed with these versions: 
![Foo](https://cdn.discordapp.com/attachments/760615360239108147/767185223312998420/unknown.png)
https://www.curseforge.com/minecraft/mc-mods/music-player/files
