### ISSUE TITLE
1.8.9 Won't load

### ISSUE THREAD

**Issue by lrosemey7** [MC-U-Team/Music-Player#63]
On MC 1.8.9, the latest version of both this mod and uteamcore(I'm reporting this here because I am 100% sure it is this mod) When I launch,  game will get stuck at initializing minecraft engine, modelmanager, modloader, blocks.
1. Launch MC

Shouldn't do this
![image](https://user-images.githubusercontent.com/72113421/94631942-d9f11880-028e-11eb-95a1-06e44beabcbb.png)

**Versions**
- Mod version:  music_player-1.8.9-2.1.0.84
- Minecraft version: 1.8.9
- Forge version:  forge-11.15.1.2318
- UTeamCore version:  u_team_core-1.8.9-1.3.0.63

**Log (if crash occures)**
Link to crash log Note that crash only occurs when i close the game manually https://pastebin.com/XD0jR8FN

**Comment by Alkali-1234** [comment]
For me it would just crash. Im using forge

**Comment by HyCraftHD** [comment]
Do you have patcher mod installed? If so that mod is incompatible with music player. I cannot fix that issue as patcher is closed source and uses heavy core modding so no way to debug that

**Comment by Alkali-1234** [comment]
> Do you have patcher mod installed? If so that mod is incompatible with music player. I cannot fix that issue as patcher is closed source and uses heavy core modding so no way to debug that

Oh i have patcher mod. I will remove patcher and try it again soon. Thanks for the info!

**Comment by HyCraftHD** [comment]
I close this issue as the incompatibility with patcher cannot be resolved right now.

**Comment by HyCraftHD** [comment]
Should be fixed with this version https://www.curseforge.com/minecraft/mc-mods/music-player/files/3841508

**Comment by Fl414r** [comment]
I have same Issue with latest Music Player version, but after I open game without Patcher once and add Patcher again, all works perfect. (this Issue first in Google if search "uteamcore 1.8.9 initialization fail")

**Comment by HyCraftHD** [comment]
Hello, can you please open an other issue with logs and all the versions please?
