### ISSUE TITLE
1.8.9 and 1.12.2 crash apon entering old playlists

### ISSUE THREAD

**Issue by AkiraKitsune** [MC-U-Team/Music-Player#64]
The issue is basically the same as written in the title, trying to access playlists causes a crash, which appears to happen when trying to read the items on the playlist. both versions appear with the same result, which is why I'm appointing them to a single bug report. However, being different Minecraft/Forge versions, I'm willing to provide details for both, including crash logs and mod versions.

To reproduce this issue, its simple
1.have music player loaded with forge
2.open the F8 tab
3.open a playlist
4.crash should appear at this step

The expectation is that it should open normally, allowing a user to see the list of songs they have added to their playlist.

Versions-1.8.9
- Mod version: music_player-1.8.9-2.1.0.84.jar
- Minecraft version: 1.8.9
- Forge version: release 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
- UTeamCore version: u_team_core-1.8.9-1.3.0.63.jar (same result follows with or without it loaded in)

Version-1.12.2
- Mod version: music_player-1.12.2-2.1.0.85.jar
- Minecraft version: 1.12.2
- Forge version: release 1.12.2-forge-14.23.5.2854
- UTeamCore version: u_team_core-1.12.2-2.2.5.147.jar

Log for Minecraft 1.8.9: https://pastebin.com/yjw3trHq
Log for Minecraft 1.12.2: https://pastebin.com/qrPAx8Ew

**Comment by HyCraftHD** [comment]
Seems to be the same as #62

**Comment by HyCraftHD** [comment]
This issue should have been fixed with these versions: 
![Foo](https://cdn.discordapp.com/attachments/760615360239108147/767185223312998420/unknown.png)
https://www.curseforge.com/minecraft/mc-mods/music-player/files
