### ISSUE TITLE
No mathes found

### ISSUE THREAD

**Issue by ghost** [MC-U-Team/Music-Player#668]
### Bug description and reproduction steps

No mathes found

### Log files and Screenshots

![2023-05-09 19 21 14](https://github.com/MC-U-Team/Music-Player/assets/123638768/ce1eea2c-ce1d-43cb-a6ef-a2e5ef8a9efb)

### Used minecraft version

1.16.x

### Used forge version

36.2.39

### Used mod version

2.3.2.183

**Comment by HyCraftHD** [comment]
Can you please upload the log file?

**Comment by ghost** [comment]
[2023-05-12-1.log](https://github.com/MC-U-Team/Music-Player/files/11461040/2023-05-12-1.log)

**Comment by HyCraftHD** [comment]
First of all you do not have uteamcore installed. That log does not match the screenshot you send in.

Second, i cannot help you, when you are using a cracked minecraft version.
