### ISSUE TITLE
[MC-Version] annoying auto skip is back

### ISSUE THREAD

**Issue by LithTheKitten** [MC-U-Team/Music-Player#69]
the youtube links are refusing to play again, this issue was brought up months ago and it seems to be back now.

**To Reproduce**
Try playing any of the songs/audio  from your lists

**Expected behavior**
The song/audio will just be skipped to another song. it will refuse to play and skip until one eventually does.
For me, my entire song list was skipped to the very last song on the list that was just added moments before i discovered this bug was back.

**Versions**
- Mod version: 1.12.2-2.1.1.92
- Minecraft version: 1.12.2
- Forge version: xxx 14.23.5.2854
- UTeamCore version: 1.12.2-2.2.5.147

**Comment by LithTheKitten** [comment]
again this issue was brought up months ago, so im guessing it has something to do with the latest update

**Comment by HyCraftHD** [comment]
Thanks. Yea it seems something in youtube broke again.
Must wait for lavaplayer to update (or the fork I'm currently using)
Will update soon

**Comment by HyCraftHD** [comment]
Should be fixed in these version:
![image](https://user-images.githubusercontent.com/7681220/98425440-5a2c4a00-2095-11eb-95f1-f196a4a2869e.png)

An other youtube bug apeared that makes playlists only play the first 100 songs ( #71 )
This issue will be fixed when the pull is merged
