### ISSUE TITLE
music from youtube doesn't work

### ISSUE THREAD

**Issue by Ijdtm7** [MC-U-Team/Music-Player#7]
when i type in any song like daft punk - da funk or deadmau5 - moar ghosts n stuff
it loads the song and then it disappears from the queue

**Comment by Ijdtm7** [comment]
i also tried letting the musicplayer with all the .jars rebuild on my launch. But it still doesnt work. It use to work but now they suddenly dont

**Comment by Ijdtm7** [comment]
especially with daft punk

**Comment by Ijdtm7** [comment]
it suddenly works now. idk wut happened

**Comment by Ijdtm7** [comment]
its still broken. When it starts playing it just drops from the queue

**Comment by MrTroble** [comment]
Hello @Ijdtm7,

can you provide more detailed information?
or even a video of what is happening?
Thanks in advance, this would help us a lot.

Cheers
~MrTroble

**Comment by Ijdtm7** [comment]
ok i will send u a .mp4 video

**Comment by HyCraftHD** [comment]
What version of this mod are you using and which forge version?

**Comment by MrTroble** [comment]
We will probably look at this tomorrow,

because it's late ... 😫 

Cheers and thanks again
~MrTroble

**Comment by Ijdtm7** [comment]
i am using music_player-1.12.2-1.2.0.5 and forge 1.12.2-forge1.12.2-14.23.5.2768 which is the recomended

**Comment by Ijdtm7** [comment]
[](https://www.youtube.com/watch?v=ACa6TSSO3iY)

**Comment by Ijdtm7** [comment]
[video](https://www.youtube.com/watch?v=ACa6TSSO3iY)

**Comment by Ijdtm7** [comment]
its a youtube video

**Comment by HyCraftHD** [comment]
Actually tested it with your configuration and could not reproduce this bug.
Are you using Windows or an other system?
Are there some errors in the log?

**Comment by Ijdtm7** [comment]
i am using Windows. Checking the logs, there is nothing from music player besides registration into the game

**Comment by HyCraftHD** [comment]
I'm currently rewriting the whole mod, so maybe just wait a little bit.

One last thought:
- Has this error occured if you paste in the url directly?
- Could it be that the video is blocked in your country?

**Comment by Ijdtm7** [comment]
It acts like it isn't actually grabbing the song from the web. It grabs the name, author, etc but makes the actual song 0:00. I am pretty sure this is on my side because I was playing it yesterday morning fine. Then I walked my dogs and when I came back it was broken

**Comment by Ijdtm7** [comment]
i am going to fire up my mc now to see if its fixed

**Comment by Ijdtm7** [comment]
checked the song its not blocked

**Comment by HyCraftHD** [comment]
Hm this is kind of strange. Could it be that your internet connection is slow?
A connection must have been established, otherwise the metadata would not have been loaded.

**Comment by Ijdtm7** [comment]
my internet is really fast. I discovered the problem. Somehow everything got messed up. I had to delete the musicplayer folder, the musicplayer config, the musicplayer mod, the uteam config, and the uteam mod. After i did that I reinstalled the mods and now i am listening to da funk
