### ISSUE TITLE
Minecraft crashes with Rubidium or Oculus mod

### ISSUE THREAD

**Issue by twojamama1** [MC-U-Team/Music-Player#783]
### Bug description and reproduction steps

Minecraft crashes with mod Rubidium or Oculus on 1.20 and 1.20.1. This wasn't happening before.
How to reproduce:
1. Run Minecraft with Rubidium or Oculus and Music Player
2. See the problem

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/110301374/8d05b67d-a95f-42f0-afd2-532f5df29648)
[crash-2023-06-17_14.19.19-client.txt](https://github.com/MC-U-Team/Music-Player/files/11778851/crash-2023-06-17_14.19.19-client.txt)

### Used minecraft version

1.20.x

### Used forge or fabric version

Forge 46.0.12

### Used mod version

2.6.0.216

**Comment by HyCraftHD** [comment]
Hello, the crash does not mention music player in any way. Are you sure it only crashes with the music player mod? And if so, can you please upload the whole log file?
Else please report the oculus

**Comment by twojamama1** [comment]
Yes. I have a lot of mods and it crashes only with music player. Where is the Full log file?

**Comment by twojamama1** [comment]
Without Rubidium and Oculus it runs normally. That means it is music player, rubidium or oculus fault.

**Comment by HyCraftHD** [comment]
Under logs/debug.log or logs/latest.log in the directory you launch minecraft from.
Can you try it without musicplayer but with rubidium and oculus just to make sure which mod crashes?

**Comment by twojamama1** [comment]
Without Rubidium, minecraft runs because Oculus needs Rubidium. But without Oculus minecraft crashes.

**Comment by twojamama1** [comment]
[latest.log](https://github.com/MC-U-Team/Music-Player/files/11779070/latest.log)
[debug.log](https://github.com/MC-U-Team/Music-Player/files/11779071/debug.log)

**Comment by HyCraftHD** [comment]
Sorry, not sure if i can follow you. Does it crash when you only have rubidium and oculus installed?

**Comment by twojamama1** [comment]
Let me check

**Comment by twojamama1** [comment]
Without Music player?

**Comment by twojamama1** [comment]
With only Music Player, Rubidium, Oculus Minecraft crashes. With only Rubidium, Oculus minecraft runs normally.

**Comment by HyCraftHD** [comment]
Thats really weird, because i tested it with musicplayer, rubidium and oculus and it runs fine.
Can you test 1.20.1?

**Comment by twojamama1** [comment]
I tested already. Same thing.

**Comment by HyCraftHD** [comment]
Hm, when does it crash? On startup?

**Comment by twojamama1** [comment]
Yes.

**Comment by HyCraftHD** [comment]
And if so, can you try to get a debug log with the crash? The logs you supplied do not hint any connection to musicplayer yet

**Comment by twojamama1** [comment]
Okey. Moment.

**Comment by HyCraftHD** [comment]
Okay wait i could reproduce now

**Comment by twojamama1** [comment]
[latest.log](https://github.com/MC-U-Team/Music-Player/files/11779134/latest.log)
[debug.log](https://github.com/MC-U-Team/Music-Player/files/11779135/debug.log)

**Comment by twojamama1** [comment]
[crash-2023-06-17_15.39.48-client.txt](https://github.com/MC-U-Team/Music-Player/files/11779141/crash-2023-06-17_15.39.48-client.txt)

**Comment by HyCraftHD** [comment]
Okay, you are using 1.20 mods on 1.20.1.

These here: 

```java
	Mod ID: 'minecraft', Requested by: 'uteamcore', Expected range: '[1.20,1.20]', Actual version: '1.20.1'
	Mod ID: 'minecraft', Requested by: 'sound_physics_remastered', Expected range: '[1.20,1.20]', Actual version: '1.20.1'
	Mod ID: 'minecraft', Requested by: 'jei', Expected range: '[1.20,1.20.1)', Actual version: '1.20.1'
```

Download the 1.20.1 versions of jei, uteamcore and sound_physics_remastered

**Comment by HyCraftHD** [comment]
The crash is also caused by this, because forge then do not apply the access transformers from oculus. Cryptic crash message though.

**Comment by HyCraftHD** [comment]
So either update all mods to 1.20.1 or downgrade all your mods to 1.20

**Comment by HyCraftHD** [comment]
Let me know if it work

**Comment by twojamama1** [comment]
Could I just delete these 3 mods for now?

**Comment by twojamama1** [comment]
With these 3 deleted, Same thing happens

**Comment by HyCraftHD** [comment]
No, because music player needs uteamcore

**Comment by HyCraftHD** [comment]
You need to install the right versions. Can you screenshot me a list of your mods, and your used forge version?

**Comment by twojamama1** [comment]
Okey, I will do it later because i need to go right now.

**Comment by twojamama1** [comment]
I am sorry. It was Rubidium bug. I am closing this issue.
