### ISSUE TITLE
Crashing at initialization 1.14.2

### ISSUE THREAD

**Issue by HyperZero64** [MC-U-Team/Music-Player#8]
When I attempt to load MC with this mod along with the U core, I crash before/at initialization. When I'm booted back to the launcher I get this error: Error: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft;
Along with the following crash log:
[crash-2019-06-23_08.11.36-client.txt](https://github.com/MC-U-Team/Music-Player/files/3317888/crash-2019-06-23_08.11.36-client.txt)

**Comment by HyCraftHD** [comment]
It seems you are using an non obfuscated version.
Is it this file?
https://minecraft.curseforge.com/projects/music-player/files/2728345

**Comment by HyperZero64** [comment]
Yeah, that's the one. Only, the file I have, has -dev at the end. It's this to be exact: 
music_player-1.14.2-2.0.0.11-SNAPSHOT-dev

**Comment by HyCraftHD** [comment]
Thats the wrong one!
Don't use the dev file if you are using it in the normal minecraft environment and not the eclipse one.
Use this file instead: https://minecraft.curseforge.com/projects/music-player/files/2728345/download

**Comment by HyperZero64** [comment]
I've downloaded the non dev file. I think i've realized my mistake now. i'll test and see if this works.

**Comment by HyperZero64** [comment]
Okay, im all loaded up. I have to start reading the mods titles lol everything seems to be fine on my end. I really feel stupid now. XD
