### ISSUE TITLE
[MC-Version] 1.20.1

### ISSUE THREAD

**Issue by RavenFlip** [MC-U-Team/Music-Player#808]
### Bug description and reproduction steps

Everytime i launch the game a "Resource Reload Failed" and when i join a world/server my game crashes, and its completely fine if i dont have the mod on

### Log files and Screenshots

e

### Used minecraft version

1.20.x

### Used forge or fabric version

1.20.1

### Used mod version

1.20.1 2.6.0.217

**Comment by HyCraftHD** [comment]
Please upload the log of the crash here. There is not much to go on by your description
