### ISSUE TITLE
[1.19.2] Cannot create music player instance. This is a serious bug and the mod will not work.

### ISSUE THREAD

**Issue by bryinabrt** [MC-U-Team/Music-Player#809]
### Bug description and reproduction steps

I was trying to run a an instance of Prominence (Fabric) with Music Player added to it, it worked first time, but now it doesn't want to run anymore.

### Log files and Screenshots

[crashlog.txt](https://github.com/MC-U-Team/Music-Player/files/12099703/crashlog.txt)

### Used minecraft version

1.19.x

### Used forge or fabric version

0.14.21

### Used mod version

2.4.1.20

**Comment by HyCraftHD** [comment]
Twitch.tv seems to be not reachable on your end. Can you just try again?
