### ISSUE TITLE
1.19.2-rapidly scrolling songs and not playing wail having the connection to service

### ISSUE THREAD

**Issue by xxxkingxl** [MC-U-Team/Music-Player#814]
### Bug description and reproduction steps

1, make a playlist on yt music
2.  share playlist and copy url
3. make playlist in mod
4. paste url
5. play playlist in loop
6. after some time ⌚
7. stops playing and scrolls rapidly between songs
8. not notes 't a crash after update: 2.5.1.224
(note:) its a bit random when it happens and doesn't happen
### Log files and Screenshots

console log:
https://paste.atlauncher.com/view/cc6c1239-56b7-4974-8c34-138d6806e678

### Used minecraft version

1.19.x

### Used forge or fabric version

forge 43.2.21

### Used mod version

2.5.1.224

**Comment by xxxkingxl** [comment]
in the forge version are 2 dots instead of 1.
did that on accident

**Comment by xxxkingxl** [comment]
I can enjoy this mod if it works
I include this mod in every modpack even if its made by someone else : )

**Comment by xxxkingxl** [comment]
my playlist that I used: https://music.youtube.com/playlist?list=PLyVbW2esMvj-ejTZeD5kC-WIYI9zk51ur&feature=share
I tested some older playlist too
when I notes't that the playlist was hidden and used a link to find it. it should just work. this methode is the methode that I used a lot whitout this happening

**Comment by xxxkingxl** [comment]
It works again for a moment, It could stop working...
I am gonne enjoy it as long as I can

**Comment by HyCraftHD** [comment]
YouTube appeared to have temporarily blocked your IP. Should be fixed by just waiting some time

**Comment by PetyaIsInControl** [comment]
had this same issue and i waited some time and it worked fine

**Comment by HyperMan19680** [comment]
Had a similar issue on 1.12.2. I feel something needs to be done to properly fix this.

**Comment by Rainstripes** [comment]
I have this issue as well. Same steps, version, & everything, though mines is in fabric. So it just stops by itself after a while?

**Comment by Catomax262** [comment]
> YouTube appeared to have temporarily blocked your IP. Should be fixed by just waiting some time

Why does this happen? Is there a way for this to simple cease happening????

**Comment by HyCraftHD** [comment]
Will be fixed soon with an update to lavaplayer as youtube changed some internal stuff again

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
