### ISSUE TITLE
Playback speed settings

### ISSUE THREAD

**Issue by Loggy98** [MC-U-Team/Music-Player#815]
### Detailed description of the feature

A playback speed setting, or slider, like what exists on YouTube with 1.5, 2, 2.5, settings, and so on. Including hotkeys that increase the speed up or down by a .5 increment, so you can change the speed on the fly.

I use this mod to listen to podcasts/debates and such from YouTube while I play. But sometimes I want to listen to something that ends up being way too long. So I end up needing to open YouTube in a browser tab in the background just to use this feature, which defeats the purpose of using the mod, and means I can't use hotkeys from within the game.

### Verify feature request

- [x] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
Thanks for your suggestion!
It's now possible in the latest 1.20.1 version to change the playback speed and the pitch in the settings menü.
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/8cf010a5-2d84-4c8f-8486-1b8f4a5fd4db)
