### ISSUE TITLE
1.20.1 Music doesn't play and skips repeatedly

### ISSUE THREAD

**Issue by KingToastIst** [MC-U-Team/Music-Player#821]
### Bug description and reproduction steps

When I try to play music, it immediately stops and doesn't play and skips to the next one where it happens again.
It was just working yesterday and I have no idea why this is happening.

### Log files and Screenshots

N / A

### Used minecraft version

1.20.x

### Used forge or fabric version

Fabric

### Used mod version

music_player-fabric-1.20.1-2.6.0.226.

**Comment by HyCraftHD** [comment]
Thanks for the report, will be fixed soon with an update to lavaplayer as youtube changed some internal stuff again

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)

**Comment by InsaneAsian** [comment]
Having the same issue in 1.19.3, any ETA on fixing that?

Thank you.

Edit: Downloading music works however though, I'll do this for now till it is fixed.

**Comment by HyCraftHD** [comment]
Update to 1.19.4 or downgrade to 1.19.2.
(1.19.3 is an unsupported minor version)
