### ISSUE TITLE
1.20.1 Music skips and doesn't play

### ISSUE THREAD

**Issue by isaacdog1470** [MC-U-Team/Music-Player#822]
### Bug description and reproduction steps

When I play music, it immediately stops and skips to the next song and doesn't play no matter what I try, I have all the requirments and most recent api and fabric version for 1.20.1, This first time I used this so I might be using it wrong but if someone could help me thank you very much

### Log files and Screenshots

Can't put a video here

### Used minecraft version

1.20.x

### Used forge or fabric version

fabric

### Used mod version

music_player-fabric-1.20.1-2.6.0.226.

**Comment by LordRCJAI** [comment]
Same

**Comment by HyCraftHD** [comment]
Thanks for the report, will be fixed soon with an update to lavaplayer as youtube changed some internal stuff again

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
