### ISSUE TITLE
[1.12.2] Skipping Issue

### ISSUE THREAD

**Issue by Viomeme** [MC-U-Team/Music-Player#823]
### Bug description and reproduction steps

1. I go to add a YouTube song to the playlist
2. I hit play and the song immediately skips to the next one in the playlist
3. Somewhat inconsistent because not all regular videos will play, and music videos never will.
4. If it helps, I'm playing the Sevtech Modpack when this issue occurs

### Log files and Screenshots

[latest.log](https://github.com/MC-U-Team/Music-Player/files/12327534/latest.log)

### Used minecraft version

1.12.x

### Used forge or fabric version

Forge 14.23.5.2860

### Used mod version

1.12.2-2.1.1.219

**Comment by HyCraftHD** [comment]
Thanks for the report, will be fixed soon with an update to lavaplayer as youtube changed some internal stuff again

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
