### ISSUE TITLE
[1.18.2] 90% of songs don't play even if they're from the same YT playlist

### ISSUE THREAD

**Issue by Catomax262** [MC-U-Team/Music-Player#824]
### Bug description and reproduction steps

1. Start the game
2. Enter music player
3. Save an entire YT playlist
4. Play any song from the playlist
5. Some will play, others just won't

Weirdest thing is that I have a really good internet connection.

### Log files and Screenshots

latest.log: https://mclo.gs/qC2CAvI

### Used minecraft version

1.18.x

### Used forge or fabric version

40.2.5

### Used mod version

2.3.4.223

**Comment by HyCraftHD** [comment]
Thanks for the report, will be fixed soon with an update to lavaplayer as youtube changed some internal stuff again

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
