### ISSUE TITLE
Youtube music does not play

### ISSUE THREAD

**Issue by SuperMarioTechGuy** [MC-U-Team/Music-Player#827]
### Bug description and reproduction steps

It worked before but now it doesn't every time I play it It seems to be working but it is stuck at 0:00 idk what I did wrong
Soundcloud works perfectly fine

### Log files and Screenshots

I get this every time I play youtube music
![log](https://github.com/MC-U-Team/Music-Player/assets/131635742/a103b272-bb9c-41a7-9b1b-39f573def1bc)

### Used minecraft version

1.18.x

### Used forge or fabric version

40.2.10

### Used mod version

2.3.4.223

**Comment by Catomax262** [comment]
Bruh Lavaplayer is sure something hard to work with, it's been a week and this is unsolved, f*ck Youtube changing code

**Comment by HyCraftHD** [comment]
Calm down. It is an open source project and has no obligation to fix things fast.

Either way, should be fixed in these versions:
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
