### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Az45** [MC-U-Team/Music-Player#829]
### Bug description and reproduction steps

I had the music player mod for a bit and it was working fine until a few days ago where it would just auto skip all songs besides 1 on only one playlist the rest of the playlist nothing played and it was all just skipped.

### Log files and Screenshots

.

### Used minecraft version

1.20.x

### Used forge or fabric version

47.1.3

### Used mod version

2.6.0.226

**Comment by lucreator245** [comment]
Had the same issue. All my songs in my playlist just skip through. It happens with all my playlists.

**Comment by SirMishaa** [comment]
Same for me

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
