### ISSUE TITLE
[1.12.2] All youtube musics were failed to play.

### ISSUE THREAD

**Issue by MicroNeutron** [MC-U-Team/Music-Player#830]
### Bug description and reproduction steps

All youtube musics were failed to play. Only on Youtube. Soundcloud is normal. 

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/90130404/1bec15e5-2125-4d10-97e2-b6f3a5a14381)
It didn't crash but just skip the song. 

### Used minecraft version

1.12.x

### Used forge or fabric version

14.23.5.2860

### Used mod version

2.1.1.219

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
