### ISSUE TITLE
[1.8.9] 

### ISSUE THREAD

**Issue by Macaron27** [MC-U-Team/Music-Player#831]
### Bug description and reproduction steps

Music doesn't play

### Used minecraft version

1.8.x

### Used forge or fabric version

11.15.1.2318

### Used mod version

2.1.1.218

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
