### ISSUE TITLE
[1.14.2] Crash when trying to Load Folder

### ISSUE THREAD

**Issue by kenster1488** [MC-U-Team/Music-Player#9]
Title pretty much explains it. I have the latest versions for Music Player and uteamcore for 1.14.2, and Forge 26.0.63. When I go to the menu, make a new playlist, and hit "Load Folder", the game closes with this error:
https://puu.sh/DMI5G/159eeacea1.png

Here is the crash log, if it may help:
[crash-2019-06-30_13.21.01-client.txt](https://github.com/MC-U-Team/Music-Player/files/3342575/crash-2019-06-30_13.21.01-client.txt)

**Comment by HyCraftHD** [comment]
Thank you for reporting. I found out what caused the bug and will update 1.14.2 and 1.14.3 version asap

**Comment by HyCraftHD** [comment]
1.14.2-2.0.1.14 
1.14.3-2.0.1.15
are the fixed versions
