### ISSUE TITLE
[1.12.2] Can't search using YouTube

### ISSUE THREAD

**Issue by MeowingInsanely** [MC-U-Team/Music-Player#96]
Can't search using YouTube / No results. Sound cloud is working.

![2020-11-20_01 49 07](https://user-images.githubusercontent.com/19327202/99704145-f06b6180-2ad2-11eb-903f-59ea5c06632a.png)

- Mod version: 1.12.2-2.1.0.85
- Minecraft version: 1,12.2
- Forge version: forge-14.23.5.2838
- UTeamCore version: 1.12.2-2.2.5.147
Note: Using RLCraft Modpack through Twitch.

Minecraft Log Output:
01:49:00.830
STDERR
lava-daemon-pool-info-loader-2-thread-1
[org.slf4j.impl.SimpleLogger:write:318]: [lava-daemon-pool-info-loader-2-thread-1] W
ARN com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider - Failed to match ytInitialData JSON object

**Comment by HyCraftHD** [comment]
Please use an updated version. Your version is several months old.

**Comment by HyCraftHD** [comment]
This here is the latest version for 1.12.2 currently: https://www.curseforge.com/minecraft/mc-mods/music-player/files/3105810
