### ISSUE TITLE
1.20.1 forge, tracks not loading

### ISSUE THREAD

**Issue by senluo0** [MC-U-Team/Music-Player#985]
### Bug description and reproduction steps

The tracks previously added from youtube are not loading, as shown by the screenshot. However, newly added tracks do load.

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/162489502/615cb4b0-1890-4c4b-9722-4b53f1348567)

https://mclo.gs/JDtFHtq

### Used minecraft version

1.20.x

### Used forge or fabric version

47.1.43

### Used mod version

2.7.0.236

**Comment by HyCraftHD** [comment]
Can you upload the log file?

**Comment by Fl414r** [comment]
Can confirm if needed. Seems like Youtube changed something. Other methods works as usual

**Comment by BioscarOG** [comment]
For me it happens here and there, it either doesn't load and I gotta restart Minecraft or I have to load a SoundCloud playlist first then it loads.

However after a bit it stops working, just not playing music that comes from YouTube links specifically, and I dunno why-

**Comment by senluo0** [comment]
> Can you upload the log file?

sorry i was busy, i will do it now.

**Comment by HyCraftHD** [comment]
Update to the latest version of musicplayer please
