### ISSUE TITLE
[1.12.2] Can't search or use YouTube URLs

### ISSUE THREAD

**Issue by lucasthech** [MC-U-Team/Music-Player#986]
### Bug description and reproduction steps

Basically whenever I try to put a YouTube video or playlist URL it gives this error:

![image](https://github.com/MC-U-Team/Music-Player/assets/53277302/091516a8-e1dd-4597-a32e-771b915a0db7)

_latest.log included bellow_

### Log files and Screenshots

[latest.log](https://github.com/MC-U-Team/Music-Player/files/14516226/latest.log)

### Used minecraft version

1.12.x

### Used forge or fabric version

Forge 14.23.5.2859

### Used mod version

2.1.1.228

**Comment by lucasthech** [comment]
I've tried to fix this bug since yesterday, restarted Minecraft several times and nothing, but just after I opened this issue the mod is working normally for some reason, so fixed, i guess.

And just to note, I also tried again when writing the issue to take the screenshot of the error, so it fixed itself right before I published the issue

Edit: If someone can explain what happened using the log I provided, please tell me :)

**Comment by lucasthech** [comment]
Reopened as the error came back after restarting Minecraft... I will keep this open as it doesn't fixes itself permanently

**Comment by MicroNeutron** [comment]
same

**Comment by HyCraftHD** [comment]
Update to the latest version of musicplayer please
