### ISSUE TITLE
[1.16.5] Can't search up/Add youtube links

### ISSUE THREAD

**Issue by Emmet1119** [MC-U-Team/Music-Player#987]
### Bug description and reproduction steps

I cannot seem to add or search youtube links and the ones I had put in Prior just auto skips forcing me to use Soundcloud as a source.

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Music-Player/assets/19894390/6d95079c-8a92-4462-baaf-ec194da11d2b)

### Used minecraft version

1.16.x

### Used forge or fabric version

Forge

### Used mod version

2.3.2.231

**Comment by lucasthech** [comment]
Same thing is happening to me, maybe youtube updated again

**Comment by omegad714** [comment]
Happened to me too

**Comment by TREESTANJUDE** [comment]
Yeah it seems you can even play songs aswell on my end

**Comment by HyCraftHD** [comment]
Yes, youtube broke again, update is on the way, but it takes some time to update for all versions

**Comment by Bloxxer14neuro** [comment]
I'm having the same issue lol I thought that deleting all my playlists would fix the problem but it didn't

**Comment by Dragonsrule3194** [comment]
I still have this problem

**Comment by NathxnAzuur** [comment]
i have that problem

**Comment by HyCraftHD** [comment]
Update to the latest version of musicplayer please
