### ISSUE TITLE
every youtube track says Loading infortmation for a youtube link failed

### ISSUE THREAD

**Issue by Blackstorm1411** [MC-U-Team/Music-Player#988]
### Bug description and reproduction steps

I just started Minecraft and then I had this problem .... hilfe :(

### Log files and Screenshots

![Screenshot (113)](https://github.com/MC-U-Team/Music-Player/assets/163746354/75edcaa0-4986-4351-9c0a-d742a4aa31cb)

### Used minecraft version

1.20.x

### Used forge or fabric version

Fabric

### Used mod version

Music-Player-Fabric-1.20.2-2.7.0.237 , U-Team-Core-Fabric-1.20.2-5.2.0.270

**Comment by HyCraftHD** [comment]
See #987

**Comment by Blackstorm1411** [comment]
oh ok tell me when its fixed

**Comment by HyCraftHD** [comment]
Update to the latest version of musicplayer please. 1.20.1 and 1.20.4 are supported minecraft versions!
