### ISSUE TITLE
[1.20.1] [Fabric] Music auto skips randomly

### ISSUE THREAD

**Issue by EnderGirl1500** [MC-U-Team/Music-Player#990]
### **Description**
The music is skipped randomly for no reason, only a few songs stay till the end. I tried deleting this mod's key binds just to see if they were glitched or something but it's still happening.

### **Steps to reproduce**
1. Install mod.
2. Create your first playlist.
3. Select music from YouTube.
4. Start the playlist.
5. See bug.

### **Additional comments**
This happened months ago, and I ended up uninstalling the mod. Today I installed it again to see if this was fixed, but it's still the same.
I use the "random" button but the auto skip happens when playing songs in order too.

### Log files and Screenshots

[logs](https://github.com/MC-U-Team/Music-Player/files/14726003/latest.log)
[video](https://medal.tv/es/games/minecraft/clips/22sD58sHI9CBtk/d1337LCpfVKh?invite=cr-MSxjVm0sMTc2NDQ5NzQyLA)

### Used minecraft version

1.20.x

### Used forge or fabric version

Fabric 0.15.7

### Used mod version

2.7.0.236

**Comment by EnderGirl1500** [comment]
Update: tried creating a new playlist and adding music from SoundCloud. The bug is still there.

**Comment by HyCraftHD** [comment]
Update to the latest version of musicplayer please
