### ISSUE TITLE
[1.20.1] [v2.7.0.236] [Fabric 0.15.7] broken all :/

### ISSUE THREAD

**Issue by bafb** [MC-U-Team/Music-Player#991]
### Bug description and reproduction steps

with the latest updates it broke... :/ it does not play any playlist or track, whether those that had been configured before the update, It doesn't let you add new ones either...

### Log files and Screenshots

![Captura de pantalla 2024-03-23 124927](https://github.com/MC-U-Team/Music-Player/assets/139619873/315b1c3d-d681-4c16-abe5-e0b7b82068c2)
![Captura de pantalla 2024-03-23 124831](https://github.com/MC-U-Team/Music-Player/assets/139619873/0ae3d16a-a1a4-45b4-a7c8-f90b69477db8)
![Captura de pantalla 2024-03-23 124731](https://github.com/MC-U-Team/Music-Player/assets/139619873/03ad3c27-8f94-4c60-b6bf-985523bfd384)

### Used minecraft version

1.20.x

### Used forge or fabric version

0.15.7

### Used mod version

v2.7.0.236

**Comment by HyCraftHD** [comment]
Update to the latest music player version
