### ISSUE TITLE
[request] add support to Spotify

### ISSUE THREAD

**Issue by bafb** [MC-U-Team/Music-Player#992]
### Detailed description of the feature

add the support for the mod can play spotify playlists 

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
Theoretically spotify playback via youtube has been added in the latest 1.20.4 version. It requires adding your own api key to the launch parameters and is not an endorsed feature for now. (https://github.com/MC-U-Team/Music-Player/blob/9702aa97a8bae8d7f2f5cc29245fe5f494c60a57/musicplayer-lavaplayer/src/main/java/info/u_team/music_player/lavaplayer/sources/AudioSources.java#L33)
