### ISSUE TITLE
[MC-Version] any

### ISSUE THREAD

**Issue by loti1234** [MC-U-Team/Music-Player#993]
### Bug description and reproduction steps

1. open game with music player mod
2. open music player
3. cant listen to music because it says "loading information for youtube track failed" and you cannot add new music to a playlist and it says "something went wrong when looking up the track"
potential solution is to update the mod again cuz i think this is because youtube updated their site again

### Log files and Screenshots

[latest.log](https://github.com/MC-U-Team/Music-Player/files/14736502/latest.log)

### Used minecraft version

1.19.x

### Used forge or fabric version

43.3.8

### Used mod version

latest

**Comment by cattotaco** [comment]
same thing for me, only soundcloud works.

**Comment by PlayfulPiano** [comment]
Can confirm I'm noticing this issue with 1.12.2 as well.

**Comment by HyCraftHD** [comment]
Please use the latest music player version
