### ISSUE TITLE
Music Player Mod from YouTube

### ISSUE THREAD

**Issue by SlenderMan096** [MC-U-Team/Music-Player#994]
### Bug description and reproduction steps

When I write the type of music I like on music player mod in Minecraft 1.12.2, it says "Something went wrong when looking up the track"

### Log files and Screenshots

![2024-03-29_13 59 40](https://github.com/MC-U-Team/Music-Player/assets/165346874/f75740b9-8138-45ed-a7d1-f0158822693e)

### Used minecraft version

1.12.x

### Used forge or fabric version

Forge - 14.23.5.2859

### Used mod version

music_player-1.12.2-2.1.1.228.jar

**Comment by SlenderMan096** [comment]
Please, help me to find out how to fix this issue...

**Comment by Dragonsrule3194** [comment]
I have this same issue on 1.20.2

**Comment by HyCraftHD** [comment]
Use the latest 1.12.2 version.

(1.20.2 is not supportzed anymore, please use 1.20.1 or 1.20.4)
