### ISSUE TITLE
[MC-Version] 

### ISSUE THREAD

**Issue by Prawn101** [MC-U-Team/Music-Player#995]
### Bug description and reproduction steps

ik youtube doesnt work at the moment so i tried all the other ones that should work but they do not i am using the newest 1.19.2 version so if 1.19 isnt supported anymore or if its something im doing

### Log files and Screenshots

.

### Used minecraft version

1.19.x

### Used forge or fabric version

forge

### Used mod version

1.19.2-2.5.1.233

**Comment by HyCraftHD** [comment]
Use the latest version please: https://www.curseforge.com/minecraft/mc-mods/music-player/files/5302426
